### ISSUE TITLE
Privacy switch enabled when media player gets deactivated

### ISSUE THREAD

**Issue by aqwserf** [roleoroleo/yi-hack_ha_integration#102]
Hi!

Moving forward on my automation, I noticed that when I deactivate the media player in HA, the privacy switch is automatically activated, with around a 20s delay:

![image](https://user-images.githubusercontent.com/29235861/205026206-5f0cb305-114d-4693-adb7-6497d2950f04.png)

Same behavior happens when I activate the media player, the privacy switch is set to off:

![image](https://user-images.githubusercontent.com/29235861/205026251-34980da9-e23e-45f6-b5c9-63d736075dce.png)

I've tested on both MStar and Allwinnerv2, same behavior.

FYI, MQTT is disabled on every camera as I use Frigate for motion detection, but I guess it has not impact as these 2 controls use API.

BTW, no matter if media player is on or off, I can play TTS using HA TTS service. Is there another purpose for this switch?

Thanks!

**Comment by aqwserf** [comment]
Hum, after reading the code, I guess why it's happening:

https://github.com/roleoroleo/yi-hack_ha_integration/blob/9910c442ff8023c5115edcc56f7836b8e0cff70e/custom_components/yi_hack/media_player.py#L151-L152

https://github.com/roleoroleo/yi-hack_ha_integration/blob/9910c442ff8023c5115edcc56f7836b8e0cff70e/custom_components/yi_hack/media_player.py#L166-L167

So my question is why? We should be able to turn on/off the media player without impacting privacy? Or again, I don't get the purpose of media player ^^

**Comment by roleoroleo** [comment]
You are right.
By design, media_player switch and privacy switch have the same behavior.
I should change media_player switch to disable tts (or media playing in generale) when it's switched off.

**Comment by aqwserf** [comment]
Ok, so if I understand correctly, privacy switch is impacted media_player switch, and media_player switch has not impact right?
