### ISSUE TITLE
Consider support xiaoyi Y4 with IFCN Y39U1E?

### ISSUE THREAD

**Issue by shiningbridge** [roleoroleo/yi-hack_ha_integration#103]
Came across the post here and tried to use **y29ga** hack for **xiaoyi Y4 IFCN**. 

But obviously it failed. the hack stuck and I cannot restore the camera now. 

Did a backup like this. 
[y4_IFCNY39U1E_backup.zip](https://github.com/roleoroleo/yi-hack_ha_integration/files/10181127/y4_IFCNY39U1E_backup.zip)

The homever.txt file is backed up when I did the hack. All other file is for the backup original.

**Comment by roleoroleo** [comment]
I can confirm that your cam is a y29ga.
And the folder Factory.done means that the hack worked.

> But obviously it failed. the hack stuck and I cannot restore the camera now.

Does the camera start when you remove the sd?

**Comment by shiningbridge** [comment]
Yes. Eventually I tried to remove sd card after long wait like several min.

**Comment by roleoroleo** [comment]
If the camera starts when you remove the sd card it's not bricked.
Please, try to create again the sd card after reformatting it.

**Comment by roleoroleo** [comment]
Follow the unbrick procedure explained in the wiki.
