### ISSUE TITLE
After updates 18-FeB yi-hack_ha_integration not work with Yi Dome 1080 camera with yi-hack-v5 beta-0.3.7

### ISSUE THREAD

**Issue by Harwesta** [roleoroleo/yi-hack_ha_integration#109]
yi-hack_ha_integration not work with Yi Dome 1080 camera with yi-hack-v5 latest version (beta-0.3.7)
Says me "Camera use unsupported yi-hack, please update".
After rollback to yi-hack_ha_integration to old version 25-NOV-2022 all work fine.

**Comment by luijose** [comment]
Also getting this with the yi-hack-MStar with y25 v0.4.7, with Yi 1080p Home 9FUS cam. Haven't tried updating the cam to y25 v0.4.9 (which is the latest), but was hoping I didn't have to..

**Comment by Oulewappeur** [comment]
My camera doesn't work anymore as well.
Updated Yi-hack to v0.3.3

Firmware Version	0.3.3
Base Version	8.2.0.0A_202012041528
Model Suffix	y20ga

**Comment by roleoroleo** [comment]
About v5:
https://github.com/alienatedsec/yi-hack-v5/issues/232#issuecomment-1436978627

About MStar:
If you don't want to upgrade to the last hack you can't update the integration.
I don't have the resources to support all possible combinations.

**Comment by alienatedsec** [comment]
> yi-hack_ha_integration not work with Yi Dome 1080 camera with yi-hack-v5 latest version (beta-0.3.7)

@Harwesta Try https://github.com/alienatedsec/yi-hack-v5/issues/232#issuecomment-1509373502
