### ISSUE TITLE
Guide on how to copy files

### ISSUE THREAD

**Issue by robix90** [roleoroleo/yi-hack_ha_integration#11]
Hi to all of you.

Would it be possible to have a link or someone can guide me on how to copy files?

I've created folder "yi-hack" in the root folder of cameras FTP server. Copied nano file so I can use TTS but it doesn't work.  Do i need to ssh or there is something else?

Kind regards.

**Comment by roleoroleo** [comment]
Decompress the archive in /tmp/sd/yi-hack

The binary in /tmp/sd/yi-hack/bin
The libraries in /tmp/sd/yi-hack/usr/share/...

**Comment by robix90** [comment]
> Decompress the archive in /tmp/sd/yi-hack
> 
> The binary in /tmp/sd/yi-hack/bin
> The libraries in /tmp/sd/yi-hack/usr/share/...

Thank you for reply Roleoroleo

When you say "decompress" do you mean login in ftp server of camera and manualy (right click with mouse -- new folder)?

or should I do it on sd card before inserting it in?

That is part what I don't get.

**Comment by roleoroleo** [comment]
It's the same.

**Comment by divemasterjm** [comment]
hi @roleoroleo in order to use media player it is needed to copy the tts (yi-hack utils) files? if yes where (directory) i have to copy those files in camera sd?

**Comment by roleoroleo** [comment]
media player uses the standard tts engine included in ha.
You have to enable it in your configuration.

speak service instead use local tts service and you need to install nanotts.

**Comment by jorgedeand-hacs** [comment]
Are all files under 'usr/share/pico/lang' necessary?
I can only copy 3 files, so far. After that it says no space left on device.

**Comment by roleoroleo** [comment]
Copy the files in /tmp/sd/yi-hack/usr/share/pico/lang
And remove the file you copied in /usr

**Comment by robix90** [comment]
Just a little note for newbs like me. /tmp/sd IS your SD card root folder. You don't need to create it
