### ISSUE TITLE
v0.4.5 - yi-hack-v5 related issues

### ISSUE THREAD

**Issue by alienatedsec** [roleoroleo/yi-hack_ha_integration#113]
I am testing your commits and wondering if the code is now covering requirements for more topics to be advertised

```
Logger: homeassistant.config_entries
Source: custom_components/yi_hack/__init__.py:74
Integration: Yi Home Cameras with yi-hack ([documentation](https://github.com/roleoroleo/yi-hack_ha_integration), [issues](https://github.com/roleoroleo/yi-hack_ha_integration/issues))
First occurred: 11:56:58 (2 occurrences)
Last logged: 12:03:19

Error setting up entry yi_hack_v5_b578a4 for yi_hack
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/yi_hack/__init__.py", line 74, in async_setup_entry
    CONF_VEHICLE_DETECTION_MSG: mqtt[CONF_VEHICLE_DETECTION_MSG],
KeyError: 'AI_VEHICLE_DETECTION_MSG'
```

Does the front-end need updating to cover additional topics? There is no vehicle detection setting (and possibly other topics) even supported by the old platform.

https://github.com/alienatedsec/yi-hack-v5/blob/2110360dd79dbd9369153e06f72b50d60350c2ed/src/static/static/home/yi-hack-v5/script/mqtt_advertise/mqtt_adv_homeassistant.sh#L27-L44

https://github.com/alienatedsec/yi-hack-v5/blob/2110360dd79dbd9369153e06f72b50d60350c2ed/src/www/httpd/htdocs/pages/mqtt.html#L98-L168

**Comment by roleoroleo** [comment]
Please, try this commit:
https://github.com/roleoroleo/yi-hack_ha_integration/commit/216597bf4cda290e27bb0bac9130ac999bf3d32e

**Comment by alienatedsec** [comment]
So, there is a problem, but I don't know where. I already made a comment on the mqttv4 side https://github.com/alienatedsec/yi-hack-v5/commit/6acca79cf591b7faa8de6a0a898cc62c38190560#commitcomment-109026051, which is another issue.

However, there are some weird issues, which we discussed outside of GitHub, and after several weeks of testing, I am struggling to understand them.
First of all, having Audio enabled - if using the Lovelace card code, it works (despite performance issues) in the dashboard (with sound) e.g.,

```
type: 'custom:webrtc-camera'
entity: camera.yi_hack_m_XXXXXX_cam
ui: true
```

![image](https://user-images.githubusercontent.com/73167064/232166633-54478844-6295-4840-9a67-a61dff790213.png)

Having said that, I go to the camera device, and when clicking on the highlighted below, to see the stream, it becomes unavailable.

![image](https://user-images.githubusercontent.com/73167064/232166307-0174299b-88b3-438d-962b-75a0960c3cf6.png)

If I disable audio, it works as normal within the device view. And yes, the performance is much better in the Lovelace dashboard without audio - but that is another problem.

![image](https://user-images.githubusercontent.com/73167064/232167341-67d40d93-260b-4589-89ca-702335cbb43c.png)

**Comment by roleoroleo** [comment]
Similar behavior with my cam, but not the same.
When I click on the sensor:
![immagine](https://user-images.githubusercontent.com/39277388/232210807-58a8d9ce-b522-409a-a642-60ef93eb6193.png)
it becomes unavailable, but it comes back "On" after a couple of seconds.
Could you check if mqttv4 process dies?

**Comment by roleoroleo** [comment]
When I have this problem ha log shows this:
![immagine](https://user-images.githubusercontent.com/39277388/232223372-a8d83439-cdee-4b60-9fbe-3278828eaf92.png)
