### ISSUE TITLE
Outdoor Camera - RTSP stream unavailable

### ISSUE THREAD

**Issue by fibilt** [roleoroleo/yi-hack_ha_integration#115]
Firmware Version	0.2.6
Base Version	11.1.26.1_202301191526
Model Suffix	h30ga

RTSP stream is very unreliable after updating to 0.2.6 and 11.1.26.1. I have noticed that very frequently, the camera gets unresponsive for some time when trying to stream video via RTSP, and then it recovers automatically from it.

Integration with home assistant does not work either after the update. When I try to stream video, I get the following error in HA:

2023-03-03 16:18:37.410 ERROR (SyncWorker_1) [custom_components.yi_hack.camera] Fetch snapshot image failed from yi_hack_a2_0efa89_cam, falling back to FFmpeg; HTTPConnectionPool(host='192.168.145.122', port=8080): Read timed out.

motion detection cam snapshot does not work either. 

Is this a known bug of 0.2.6 version?  Can someone with same camera confirm if they dont have any problem with 0.2.6 version please?

<img width="363" alt="image" src="https://user-images.githubusercontent.com/49229847/222774863-6580dbb3-3094-4254-b7f3-342f209c0740.png">

**Comment by McGiverGim** [comment]
It seems I've a similar problem. My camera does not work in Home Assistant, I'm not sure if the problem is the integration update or the Home Assistant update to 2023.3.

**Comment by fibilt** [comment]
My camera stopped working in home assistant  when I updated the camera hack firmware (all winners v2) and camera base firmware. I have not updated to home assistant 2023.3 yet, HA update can’t be the problem.

Something interesting is that I can stream video with VLC for instance with no issues.

Something I noticed too is that high level resolution snapshot does not work either. I don’t know if the issue is related.

**Comment by McGiverGim** [comment]
In my case, both snapshots work.

**Comment by McGiverGim** [comment]
I can see this error in HA:
```
2023-03-04 08:52:32.002 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: Camera is off
```
but the camera is on, for sure, that is at least what appears in the camera web and the VLC can stream without problem. I have tried to enable de "RTSP alternative server", without luck. Remove and add again the integration to HA, without luck.

@roleoroleo some idea of what can be wrong?

**Comment by McGiverGim** [comment]
@fibilt this is very strange. If tried to add the camera as "onvif" camera, it works, and it ADDS the Onvif camera stream to the yi cam integration too. And it seems to work.

**Comment by fibilt** [comment]
Yes, I was able to add the camera as onvif too but tbh I did not find the streaming very reliable.

I also tried to add the camera using ffmpeg integration, but similar results. I wonder if the issue is caused by something added in the new hack or base firmware

**Comment by majkers** [comment]
> I can see this error in HA:
> 
> ```
> 2023-03-04 08:52:32.002 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: Camera is off
> ```
> 
> but the camera is on, for sure, that is at least what appears in the camera web and the VLC can stream without problem. I have tried to enable de "RTSP alternative server", without luck. Remove and add again the integration to HA, without luck.
> 
> @roleoroleo some idea of what can be wrong?

https://github.com/roleoroleo/yi-hack_ha_integration/issues/112
