### ISSUE TITLE
yi-hack-v5 issue with version 0.4.4

### ISSUE THREAD

**Issue by shaylami** [roleoroleo/yi-hack_ha_integration#116]
after upgrade of yi-hack it was not supported with yi-hack-v5 version 0.3.7

**Comment by fraserp** [comment]
+1 Camera has YiHack v5 0.37, Yi Hack HA Integration v0.44 -> in trying to set up (first time) I get the error "You camera has an unsupported hack version. 

Is this just a version number check mismatch (i.e. can can update the version check code to accept this version) or is this a genuine incompatibility?

**Comment by roleoroleo** [comment]
https://github.com/alienatedsec/yi-hack-v5/discussions/233
