### ISSUE TITLE
entitiys not available after upgrade to 0.4.4

### ISSUE THREAD

**Issue by SeriousPat** [roleoroleo/yi-hack_ha_integration#117]
After Upgrade to 0.4.4 the entitys doesnt work anymore.
after reinstall the integration, an reinstall entitiys, same problem.

Cams-FW: [yi-hack-Allwinner-v2](https://github.com/roleoroleo/yi-hack-Allwinner-v2)
Firmware Version | 0.2.6

Cams working fine at the webUI of the cam.

**Comment by Foguet** [comment]
I have the same problem:
Cams-FW: [yi-hack-Allwinner-v2](https://github.com/roleoroleo/yi-hack-Allwinner-v2)
Firmware Version | 0.2.6

Home Assistant 2023.3.5
Supervisor 2023.03.1
Frontend 20230309.1 - latest

**Comment by roleoroleo** [comment]
Please, try release 0.4.5

**Comment by SeriousPat** [comment]
Sorry, it dowsnt work with 4.5
![Screenshot 2023-03-21 102656](https://user-images.githubusercontent.com/98743842/226565378-644f036d-d4ff-444b-acfb-11160f06c074.png)

**Comment by roleoroleo** [comment]
Any errors in the log?

**Comment by danhajduk** [comment]
I'm having the same problem, My cameras would become unavailable for a while and then I would have to reboot the camera and then turn the camera switch off and then on using WebUI.  
this is the only thing I could find in the log files

```
Logger: homeassistant.components.stream.stream.camera.yi_hack_a2_448765_cam
Source: components/stream/__init__.py:434
Integration: Stream (documentation, issues)
First occurred: 1:27:06 PM (23 occurrences)
Last logged: 2:11:06 PM

Error from stream worker: Error opening stream (ERRORTYPE_110, Operation timed out) rtsp://10.0.0.235/ch0_0.h264
Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://10.0.0.235/ch0_0.h264 

```

**Comment by roleoroleo** [comment]
Is mqtt enabled in your ha installation?

**Comment by slimjim2234** [comment]
Same issue here.
Running y20ga Yi Hack v0.3.3
Entities do not update after 0.4.2 of yi-hack_ha_integration
Currently running 0.4.2 to get camera streams working.
Seeing similar symptoms in #115 #118

**Comment by roleoroleo** [comment]
The problem is that the camera seems to be off but it's not true.
I also own a y20ga and have no problems.
What's your fw version, I mean Yi firmware, 8 or 12?

**Comment by roleoroleo** [comment]
Please open MQTT Explorer and check if you receive stat messages when the cam starts:
![immagine](https://user-images.githubusercontent.com/39277388/227781393-9b78bc0f-99b2-4c87-b3af-cfa7a1412ed2.png)

**Comment by slimjim2234** [comment]
![image](https://user-images.githubusercontent.com/405321/227793034-741156bd-a599-454e-a664-54e6b0c10c77.png)

I got it to work with 0.4.5, but had to enable the mqtt service on the camera and all of the associated mqtt topics as well. 
Now I have a lot of duplicate entities.
Currently, the camera will not work if it is not synced with HASS over MQTT.  This is not a desirable outcome.

**Comment by danhajduk** [comment]
I got it to work on my cameras but it would only work if I disable the cloud on the camera. It does work for me because i prefer to have it disabled.

**Comment by roleoroleo** [comment]
@slimjim2234 
As you can read in the readme, this integration requires mqtt component.

But you don't have to enable mqtt discovery in the cam:
http://192.168.0.245:8080/?page=mqtt_adv
![immagine](https://user-images.githubusercontent.com/39277388/227869032-0af0765f-3820-4dbb-a703-73c123f63854.png)
mqtt discovery is mandatory if you don't want to use this integration.

Just enable this option:
![immagine](https://user-images.githubusercontent.com/39277388/227869187-f77eee91-7314-4997-9909-4f0195451212.png)
http://192.168.0.245:8080/?page=mqtt

@danhajduk 
This integration is not related to the cloud connection. It must work with or without cloud.

**Comment by SeriousPat** [comment]
@roleoroleo
Thanks, its woking now.
I just installed mqtt(mosquito) on HA and setup mqtt in the general mqtt page over the web on the cam.
Will there be the intergation in the future or will you switch for using "Mqtt Advertise & Homeassistant MQTT Discovery" only?

**Comment by roleoroleo** [comment]
> @roleoroleo Thanks, its woking now. I just installed mqtt(mosquito) on HA and setup mqtt in the general mqtt page over the web on the cam. Will there be the intergation in the future or will you switch for using "Mqtt Advertise & Homeassistant MQTT Discovery" only?

I will support both technologies but I prefer to use my integration because there are more features:
- media sources
- ptz services
- speak service
- ...

**Comment by danhajduk** [comment]
@roleoroleo Yes I understand that it is not related to cloud service, but for some reason on my 2 cameras that is the what solved it. When I turn it on the camera in the integration becomes unavailable.

**Comment by roleoroleo** [comment]
Please, explain me the sequence.
