### ISSUE TITLE
"Error requesting stream: Camera is off"

### ISSUE THREAD

**Issue by MosheTzvi** [roleoroleo/yi-hack_ha_integration#118]
Latest YiHack (0.4.4) and latest FW on my Dome Cameras (.49).  I can't get any stream or images to show in HA.  Rebooted several times.  Tried the WebRTC add-in.  By default, I get a "can't get URL for camera" error.  If I enable RTSP on the dome camera, then I get "mse: source 0 error: dial tcp IPOFTHEDEVICE:554: connect: connection refused"
What am I doing wrong? 
Cameras are on and working outside of HA.

**Comment by roleoroleo** [comment]
Check the switch:
![immagine](https://user-images.githubusercontent.com/39277388/226541874-f79b4f1f-0d62-450f-a3ac-3e1893d86e10.png)

**Comment by MosheTzvi** [comment]
It is in the state you have pictured.

**Comment by roleoroleo** [comment]
Does it work with VLC?

**Comment by MosheTzvi** [comment]
no

**Comment by roleoroleo** [comment]
Please, share your system.conf file (remove personal data, if present).

**Comment by MosheTzvi** [comment]
> 

system.conf from where?

**Comment by roleoroleo** [comment]
It's not critical but fix the option RTSP_AUDIO: it can't be empty.
The configuration is ok but rtsp doesn't work.
Check if the process is running:
`ps | grep RTSP`

**Comment by MosheTzvi** [comment]
I hard rebooted and it's working now.  thanks.
