### ISSUE TITLE
No privacy mode sensor on 0.4.5

### ISSUE THREAD

**Issue by pannal** [roleoroleo/yi-hack_ha_integration#119]
There's no privacy sensor available anymore. Calling `http://yicam1:8080/cgi-bin/privacy.sh` still works.

Firmware Version: 0.2.6
Model Suffix: r30gb

Controls:
![image](https://user-images.githubusercontent.com/1359593/230751656-628c2279-78de-4a6e-b3a8-2a098eac5b40.png)

**Comment by bedson87** [comment]
I just updated and want report it ;-) it's a very useful option for automation.  At this point, I have to turn off the camera completely so that it does not record unnecessarily, but I lose the preview.

**Comment by roleoroleo** [comment]
This is a breaking change of the last release (both hack and integration).
privacy.sh is no longer available, if you reinstall the hack from scratch the service
http://yicam1:8080/cgi-bin/privacy.sh
will not work.
The switch is replaced by switch_on that is synced with the app.

**Comment by pannal** [comment]
Oh OK. I'll stay on the legacy version, then. Thank you!

**Comment by roleoroleo** [comment]
"Switch on" in ha should work and should be synchronized with the web gui.
Please, try to remove the cam from ha and add it again.

**Comment by roleoroleo** [comment]
> The camera only turns on/off when Save Configuration is pressed as well.

Yes, the meaning is that you don't need to reboot the cam. For the other pages you need to reboot the cam.

From the images above it seems that the connection between ha and the cam doesn't work at all.
Did you configure properly mqtt?

**Comment by roleoroleo** [comment]
Yes, mqtt is mandatory.

**Comment by roleoroleo** [comment]
> Thank you, When using mqtt, is device renaming in HA still supported?

I think it's supported but I never tested.

> Also what modes have to be enabled in the mqtt config on the camera?

Set general options:
![immagine](https://github.com/roleoroleo/yi-hack_ha_integration/assets/39277388/87216a9a-b4c5-4166-ab79-e9263232ccda)

Set topic prefix:
![immagine](https://github.com/roleoroleo/yi-hack_ha_integration/assets/39277388/efb8348f-43d6-4c65-a832-42fd48d1e732)

Other options are not important.
