### ISSUE TITLE
yi hack v5 don't supported?

### ISSUE THREAD

**Issue by scheccia1** [roleoroleo/yi-hack_ha_integration#121]
{
"name":"yi-hack-v5",
"hostname":"yi-0106",
"fw_version":"0.3.7",
"home_version":"3.0.0.0D_201809111054",
"model_suffix":"yi_outdoor",
"hardware_id":"9CUS",
"serial_number":"Y961N8LSQS190916",
"ptz":"no",
"local_time":"Mon Apr 10 09:03:59 UTC 2023",
"uptime":"3114.72",
"load_avg":"7.01 6.99 6.55",
"total_memory":"30760",
"free_memory":"9332",
"free_sd":"2%",
"local_ip":"192.168.10.10",
"netmask":"255.255.255.0",
"gateway":"192.168.10.1",
"mac_addr":"60:23:A4:88:01:06",
"wlan_essid":"HomeFibraPi",
"wlan_strength":"44",
"privacy":"off" 
}
Logger: custom_components.yi_hack.config_flow
Source: custom_components/yi_hack/config_flow.py:80

**Comment by alienatedsec** [comment]
Try this @scheccia1 - it needs testing
[yi_outdoor.zip](https://github.com/roleoroleo/yi-hack_ha_integration/files/11237622/yi_outdoor.zip)

**Comment by scheccia1** [comment]
> Try this @scheccia1 - it needs testing [yi_outdoor.zip](https://github.com/roleoroleo/yi-hack_ha_integration/files/11237622/yi_outdoor.zip)

i installed it, but i don't have access to the web interface anymore, i tried via ftp but i can't access it either

**Comment by scheccia1** [comment]
all ok... i must delete old dir of configuration.
![Schermata del 2023-04-15 11-49-25](https://user-images.githubusercontent.com/1670695/232206719-1c7783bc-9030-4ed1-8fc4-35e25dac3a2f.png)

**Comment by alienatedsec** [comment]
@scheccia1 please follow this for any further pre-release testing - https://github.com/alienatedsec/yi-hack-v5/discussions/248#discussion-5090628
