### ISSUE TITLE
ip change

### ISSUE THREAD

**Issue by teopozzi** [roleoroleo/yi-hack_ha_integration#124]
hi I have a problem with YI outdoor camera allwinter 2 
sometime happen that it change ip address (I have button in home to activate or deactivate the camera and sometime is off) the yi integration recognize the camera but id doesn' work 
![image](https://user-images.githubusercontent.com/128717947/233331437-45e5e65e-5493-4443-ba8d-f49fc20bf6c1.png)
![image](https://user-images.githubusercontent.com/128717947/233331677-faee6c3d-e4bc-4205-86cb-1ddfa2a9a2e8.png)
![image](https://user-images.githubusercontent.com/128717947/233332011-56686921-9720-4877-8781-3fe08535aa0f.png)

I can only remove the camera and recreate new one 
is it possible to update only the ip address?
Matteo

**Comment by roleoroleo** [comment]
The whole procedure is based on the assumption that the camera has a static ip.
Are you able to assing a reservation with your dhcp server?

**Comment by teopozzi** [comment]
no I've tried to check the configuration of my mesh "TP-Link Deco M5 Wifi
Mesh AC1300" but I haven't found a way to enable static ip to the camera
M

Il giorno gio 20 apr 2023 alle ore 14:18 roleo ***@***.***>
ha scritto:

**Comment by teopozzi** [comment]
maybe I've found a way
let's talk to you soon
Matteo

Il giorno gio 20 apr 2023 alle ore 14:28 Matteo Pozzi ***@***.***>
ha scritto:

**Comment by roleoroleo** [comment]
You should check on your router.

**Comment by teopozzi** [comment]
hi it seem it is working right now but I have this error installing hacs app


Logger: homeassistant.setup
Source: setup.py:185
First occurred: 7 novembre 2023 alle ore 19:38:02 (1 occurrences)
Last logged: 7 novembre 2023 alle ore 19:38:02

Setup failed for media_files: Integration not found.

here is the media line of configuration.yaml

![Immagine 2023-11-08 100855](https://github.com/roleoroleo/yi-hack_ha_integration/assets/128717947/648501d7-8e61-4cfd-8722-9398187a84cf)

many thanks 
Matteo

**Comment by roleoroleo** [comment]
Why do you need media_files integration?

**Comment by teopozzi** [comment]
don't know ... I thougth it was due to the yi-hack app 
do you think I can cancel al the media_file line? is not needed by the app? 
kind regards

**Comment by roleoroleo** [comment]
It's not needed.

Maybe you need a `media_source:` line if you don't have it.

**Comment by teopozzi** [comment]
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/128717947/0f5b326c-3f7c-4a82-9d41-03a63f0ea48a)

error in the home assistant notify is now ok but I can't access to the YI camera 
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/128717947/0a86063c-dc08-40b8-a136-bc0408cdfc13)

and in the media folder
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/128717947/aa10e2fb-80c8-421f-a16f-24329759cc9b)
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/128717947/71d5980f-7e06-493e-a60f-4cbb347ad58b)
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/128717947/e2d821b6-adcc-4dc9-b950-7f75a896d55c)

**Comment by teopozzi** [comment]
all ok now 
many thanks
Matteo
