### ISSUE TITLE
binary sensor for sound detection have at intervals of 10'

### ISSUE THREAD

**Issue by ibratos** [roleoroleo/yi-hack_ha_integration#125]
Hi,
I have detected that when there is sound that I activate it, it turns on for 1' (normal), then it returns to a clean state, but it does not activate again after 9', despite the persistence of the high sound level

Yi 1080p 9FUS
Firm 12.2.x
YiHack 0.3.3

Is it normal?
Can we change interval?

**Comment by roleoroleo** [comment]
The cam sens only the "sound detection" event when the event is fired.
It doesn't send the stop command.
So, the integration set a 60 seconds off delay when it creates the binary sensor:
`self._off_delay = 60`
And there is no feedback between ha and the cam.

I think that the 9 secs interval depends on the cam, and not on the integration.
You could check this behavior reading the mqtt messages sent by the cam.
Try with MQTT Explorer or with another client.

**Comment by ibratos** [comment]
I had check it, 10' interval comes from camera, with cloud service the interval was equal

**Comment by roleoroleo** [comment]
If 60 seconds is too much, I can set it to 10.
