### ISSUE TITLE
Error getting status

### ISSUE THREAD

**Issue by nbernier** [roleoroleo/yi-hack_ha_integration#126]
I can't make the trigger to run when there is movement on my cam. Also I have this in the logs:
ERROR (SyncWorker_2) [custom_components.yi_hack.common] Failed to get status of device 

My cam is up and running, the hack is running. I can connect to ip:8080

Anyway I can see more details on the error?

**Comment by roleoroleo** [comment]
Please, give me some details.
Model suffix, firmware version, integration version, ha version...

**Comment by nbernier** [comment]
Model: RFUS
Firmware version: y291ga_0.2.6
Integration: 0.4.2
HA version: 2023.5.0

**Comment by roleoroleo** [comment]
Please, update the integration.
