### ISSUE TITLE
Cam device and entities disabled in Home Assistant

### ISSUE THREAD

**Issue by Davidd012** [roleoroleo/yi-hack_ha_integration#127]
Hi there! 

First of all thanks for your work.

I hacked my Yi camera with MStar (Last release), and I copied the custom components (0.4.5) folder in the Home Assistant config folder. I enabled on the camera the MQTT service and discovery, RTSP etc. All good with that.

In the Yi-hack addon in Home Assistant I have mostly of the things disabled, I only have access to the camera's media. The camera device is disabled, and all the other entities too.

I'm new with Home Assistant and not sure if I'm forgetting something else (additional code in config.yaml/go2rtc.yaml, an extra add-on like webrtc, or any other step process).

I saw a video of other guy, and he did the same than me, without any extra step and he has access to the camera media stream. 

Any suggestion is welcome!

![Untitled](https://github.com/roleoroleo/yi-hack_ha_integration/assets/134094870/b03e2a8d-eef5-4120-bb7e-9e2a47d29ef6)

**Comment by roleoroleo** [comment]
If you are using this integration, MQTT service discovery can be disabled.
Did you enable MQTT integration in HA?

**Comment by maobuz** [comment]
i have the same problem, after last update the camera on yi-hack do not work 
Camera firmware 0.5.2
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3

I tried to configure again but nothing
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/73724063/db7d60e2-75c1-46f6-9d2b-6c831ba63cee)

on mttq do not find the camera

Help Me !

**Comment by roleoroleo** [comment]
Please, check the log and report errors, if present.

**Comment by maobuz** [comment]
> Please, check the log and report errors, if present.

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.config_entries
Source: custom_components/yi_hack/__init__.py:164
Integration: Yi Cam con yi-hack (documentation, issues)
First occurred: 00:15:23 (1 occurrences)
Last logged: 00:15:23

Error unloading entry yi_hack_m_68e502 for yi_hack
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yi_hack/__init__.py", line 164, in async_unload_entry
    hass.data[DOMAIN].pop(entry.entry_id)
KeyError: '4b659c83240d2faa69a5693556782ee5'

**Comment by roleoroleo** [comment]
There are no "big" problems in your log.
The 1st error (KeyError) happens when you remove the cam, so it's not related to the installation/running phase.
Other errors are related to the rtsp stream.

Is mqtt broker properly configured?
Check if you disable MQTT Advertise; if you use this integration, mqtt advertise is not required.
`http://IP_OF_YOUR_CAM/?page=mqtt_adv`

**Comment by maobuz** [comment]
> There are no "big" problems in your log. The 1st error (KeyError) happens when you remove the cam, so it's not related to the installation/running phase. Other errors are related to the rtsp stream.
> 
> Is mqtt broker properly configured? Check if you disable MQTT Advertise; if you use this integration, mqtt advertise is not required. `http://IP_OF_YOUR_CAM/?page=mqtt_adv`

ok , i deleted all and reset a camera setting to default and reboot a home assistant, after reboot i reinstalled all and now 

![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/73724063/9da7e300-10dd-45e9-8039-3983e5ac4111)

it's working !
