### ISSUE TITLE
"Can't get mac address or serial number" when add camera

### ISSUE THREAD

**Issue by Steven304** [roleoroleo/yi-hack_ha_integration#128]
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/40681145/0dc2e1eb-111c-4afa-92d1-4959dffd8df6)
Hi guys, I got this message when adding camera. I have installed yi hack v4 into yi dome camera. so has anyone seen this?
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/40681145/ff0a90a0-e86b-4588-9a3a-a53e593633fa)

**Comment by roleoroleo** [comment]
This means that the cam doesn't reply to this http request:
http://192.168.1.42:8080/cgi-bin/status.json

**Comment by roleoroleo** [comment]
If your hack is v4 there's no fix.
It's not supported.
