### ISSUE TITLE
"Save video when a motion is detected" does not update properly

### ISSUE THREAD

**Issue by auanasgheps** [roleoroleo/yi-hack_ha_integration#130]
Hi,
Using this integration on HA with a r35gb running yi-hack-Allwinner-v2 version 0.2.7.

![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/20586878/ea4633a3-773c-4afe-a0c0-90f77b319395)
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/20586878/3be83870-cb2c-4517-b372-d65869ac4722)

When I toggle `Switch on/off the camera` in Yi GUI, it gets updated in HA, and vice-versa.
However, when I toggle `Save video when a motion is detected` in HA, **it does not** update the actual camera setting. If I change it in the camera, it reflects in HA.

**Comment by roleoroleo** [comment]
You are right.
Please, overwrite the files in /tmp/sd/yi-hack/bin with the content of this archive:
[save.tar.gz](https://github.com/roleoroleo/yi-hack_ha_integration/files/11747378/save.tar.gz)

**Comment by auanasgheps** [comment]
I've done it and rebooted the camera. Now it's rebooting in loops...

**Comment by auanasgheps** [comment]
Hard unplug has solved the bootloop.
Thanks, the change is now reflected! 
![immagine](https://github.com/roleoroleo/yi-hack_ha_integration/assets/20586878/2b08a68c-9218-4867-a0ac-e8aaefd50755)

![immagine](https://github.com/roleoroleo/yi-hack_ha_integration/assets/20586878/e9579be4-130e-4cb9-b5b7-e7ec576248c6)

Good to close for me if will be implemented in the next update :)

**Comment by roleoroleo** [comment]
Yes, already committed.

**Comment by auanasgheps** [comment]
Thank you!

**Comment by auanasgheps** [comment]
Hey I have an issue related to this one.
Even if the option is disabled (with the fix), the camera is still recording a video when motion is detected :(

**Comment by roleoroleo** [comment]
Does the switch change in the web interface when you change it in ha?
What does "is still recording" mean?
When the switch is off the cam should record 24h, 1 file every minute.

**Comment by auanasgheps** [comment]
> Does the switch change in the web interface when you change it in ha?

Yes.

Here's the current setting in HA:
"Save video on motion" is off
"Video switch" is on
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/20586878/92a55223-3a34-4732-aac9-e08706f10037)

in Web Interface looks correct:
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/20586878/d8c90741-f6be-47d8-8b38-c83faf0cc7dd)


> When the switch is off the cam should record 24h, 1 file every minute.

OK, so maybe I misunderstood the feature. My goal is to replicate the old "privacy" mode and disable recording while I'm at home. What setting should I switch? "Switch on/off the camera"?

**Comment by roleoroleo** [comment]
Yes, I copied how original firmware works.
When you switch off the cam, it should stop recording.

**Comment by auanasgheps** [comment]
Closing - no further action is needed.
