### ISSUE TITLE
MQTT Name changes in 2023.8

### ISSUE THREAD

**Issue by dreimer1986** [roleoroleo/yi-hack_ha_integration#133]
Recent beta of Home Assistant has some new naming regulations and causes quite some 3rd party addins to fill the logs:

![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/29841368/2c6f23b8-e5e8-4bcb-813e-1ea452140dd8)

Sources:
https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/
https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099

Here the fixing commits of Z2M as reference:
https://github.com/Koenkk/zigbee2mqtt/commit/f6196107a75f9257366505a3ad5ef7b29ff5bc1c
https://github.com/Koenkk/zigbee2mqtt/commit/df93e4c8f9490e503e5896e082fc2578f98c2e0e

**Comment by roleoroleo** [comment]
Are you using the integration or the auto-discovery feature?
My ha is updated and I have no warning messages.

**Comment by dreimer1986** [comment]
That's a good question... I just removed the addin and the entities are still there...
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/29841368/40b12fe0-a209-43ac-b238-83cd601b0ee5)
This is how my addin page looks right now. I think I have both running now that I think of it:
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/29841368/7aae1cc4-4a42-4522-8566-dea232bc0fe2)
Soo... likely my fault here ^^

**Comment by dreimer1986** [comment]
To be 100% precise. I have the Addin and as it seems at least in the past MQTT Auto discovery/at least entered the MQTT login data to the cam settings. So HA claims the device to be set up twice. And this seems to be absolutely correct.

![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/29841368/588d59d6-2254-4461-933e-002881d87ee8)

Here a lil search for the animal detection entities of two cams. The sensors are there twice and the MQTT ones are the ones it is mad at. So the addin is correct and thus my report is wrong.

I close this one and pass over to https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/687 as this is the problem I have, too. (Sure, I can remove the MQTT ones, but for now I am still not sure which ones I wanna keep.)
