### ISSUE TITLE
Cacagoo camera

### ISSUE THREAD

**Issue by Hmi04** [roleoroleo/yi-hack_ha_integration#135]
Hi, thank you for all your work.

I have a Cacagoo camera, chinese version  that works with the Yi Windows app.
Attached is the firmware dumped using the allwinner factory.sh.

Can you suggest which firmware to use?

Version: 9.0.08.04_202007241745
Serial: A2132003T076S1200728

https://drive.google.com/drive/folders/1bsNYiib3u7H189aDcVZilBr8MHOw3ir0?usp=sharing

Edit: r40ga_0.2.9 seems to work well minus the ftpd

**Comment by roleoroleo** [comment]
This is a new model, currently unsupported: q705br.
I have to check if I can support it.
Please, move the issue to Allwinner-v2 repo.
