### ISSUE TITLE
Damaged SD Card-Problem with Home Assistant

### ISSUE THREAD

**Issue by xelaftaki** [roleoroleo/yi-hack_ha_integration#138]
Hello friend.
For the past three years my Cam was performing as it should, with the yi-hack-Allwinner-v2.
3 days ago the SD card gave away. I've inserted a new one and restored my back-up from June. It was the 0.2.2 version. I can access the camera through http://192.168.XXX.YYY:8080, all good.
Until i've tried to add it through Yi hack integration to Home Assistant again. I keep getting the same error message.
Problem is that on the Maintenance Tab can't get the new version (0.3.0) -if this is the issue.

I am attaching the images: 
System (Camera web tab)
Maintenance (Camera web tab)
HASS-MSG (Home assistant error message)
![SYSTEM](https://github.com/roleoroleo/yi-hack_ha_integration/assets/100031568/3bd8ab5f-ba17-4539-bb97-7189899963db)
![MAINTENANCE](https://github.com/roleoroleo/yi-hack_ha_integration/assets/100031568/dc3f4afe-21f6-4629-b671-1295b349faa6)
![HASS_MSG](https://github.com/roleoroleo/yi-hack_ha_integration/assets/100031568/916c3726-42de-4ce0-8a00-daeba20253b3)

Any help would be greatly appreciated.
Thank you for your time.

**Comment by roleoroleo** [comment]
0.2.2 is very old, probably something is changed in the ota upgrade.
Format the sd card and install again the hack.
