### ISSUE TITLE
New media_player entity not created

### ISSUE THREAD

**Issue by divemasterjm** [roleoroleo/yi-hack_ha_integration#14]
i reload integration and reboot ha but new entity media_player is not shown

**Comment by waleed-alharthi** [comment]
@divemasterjm hi, how did you resolve this? I've run into the same issue

**Comment by divemasterjm** [comment]
> @divemasterjm hi, how did you resolve this? I've run into the same issue

no solution, sorry

**Comment by roleoroleo** [comment]
HA version?
