### ISSUE TITLE
Integration is using deprecated supported features values

### ISSUE THREAD

**Issue by Extreme79** [roleoroleo/yi-hack_ha_integration#142]
Hi!
As home assistant log is reporting me, 
_Entity camera.xxxxxxxxx (<class 'custom_components.yi_hack.camera.YiHackCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF|STREAM: 3>, please create a bug report at https://github.com/roleoroleo/yi-hack_ha_integration/issues and reference [https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation](https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation)_

**Comment by GiaMisu** [comment]
same error, these warnings appear in the logs:

Entity camera.yi_hack_m_03c4bb_cam (<class 'custom_components.yi_hack.camera.YiHackCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF|STREAM: 3>, please create a bug report at https://github.com/roleoroleo/yi-hack_ha_integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
00:02:24 – (AVVISO) helpers/entity.py - il messaggio si è verificato per la prima volta alle 00:02:24 e compare 2 volte


DEVICE_CLASS_CONNECTIVITY was used from yi_hack, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.CONNECTIVITY instead, please create a bug report at https://github.com/roleoroleo/yi-hack_ha_integration/issues
00:02:24 – (AVVISO) Sensore binario - il messaggio si è verificato per la prima volta alle 00:02:24 e compare 6 volte


SUPPORT_ON_OFF was used from yi_hack, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please create a bug report at https://github.com/roleoroleo/yi-hack_ha_integration/issues
00:02:24 – (AVVISO) Telecamera - il messaggio si è verificato per la prima volta alle 00:02:24 e compare 4 volte

**Comment by roleoroleo** [comment]
I think this issue is already fixed (but not released).
https://github.com/roleoroleo/yi-hack_ha_integration/commit/bac299058af2a887d5b8dd67611f6c0e98cf7acd
https://github.com/roleoroleo/yi-hack_ha_integration/commit/325b04687c1b600d4251dec72781934c98e2e18f

**Comment by Kaeybe** [comment]
After updating HomeAssistant, this warning appeared : 

SUPPORT_ON_OFF was used from yi_hack, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please create a bug report at https://github.com/roleoroleo/yi-hack_ha_integration/issues
SUPPORT_STREAM was used from yi_hack, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.STREAM instead, please create a bug report at https://github.com/roleoroleo/yi-hack_ha_integration/issues

**Comment by roleoroleo** [comment]
Fixed here:
https://github.com/roleoroleo/yi-hack_ha_integration/commit/7bb48091ce0f8591b4845a56194f298d2523001b
