### ISSUE TITLE
Don't record temporarily

### ISSUE THREAD

**Issue by pannal** [roleoroleo/yi-hack_ha_integration#145]
Hey there,

I'm using the HA integration with two r30gb and am able to turn them on and off. However, as the PTZ doesn't work while the cameras are off, and I have them set to a "privacy orientation" normally, I need to use the PTZ to move them to the "surveillance" orientation after turning them on.

This leads to motion being detected and videos to be saved. Can this be circumvented? Can I turn recording/motion detection off while moving them with the PTZ service?

Thank you!

**Comment by roleoroleo** [comment]
It depends on the cam, but in general it's not possible.
