### ISSUE TITLE
yi-hack-Allwinner-v2 -> PT202

### ISSUE THREAD

**Issue by AditaNi** [roleoroleo/yi-hack_ha_integration#147]
Hi,

nice job with the Hack, but....with the new SW 0.31 the PT202 is not working anymore. With previous SW is working fine.

My camera doesn't connect to my WIFI router anymore.
Instead is appearing as a stand-alone device. I can connect to it but on Configurations page there is no WIFI router to be found anymore.
It is only "Other..." appearing.
Maybe because is as "stand-alone" device it cannot search for WIFI routers?

And camera beeps each few seconds two times....wired.

Regards
Adrian

**Comment by roleoroleo** [comment]
Please, explain me better.

> Instead is appearing as a stand-alone device

Do you mean that it's working as an access point?

> And camera beeps each few seconds two times....wired.

Wired? Is it connected with an ethernet cable?

It seems that your cam lost wifi settings and maybe it's trying a pairing procedure.
There are no changes about wifi in the last release.
So, you could try to:
- remove 0.3.1 and restore 0.3.0
- reset the cam and pair it again with the app
