### ISSUE TITLE
Similar camera type?

### ISSUE THREAD

**Issue by Ryan-unity1993** [roleoroleo/yi-hack_ha_integration#148]
I have a very similar camera that uses their app to access the camera or like a third party app that uses the yi servers. I have managed to pull off the firmware from the camera and loaded onto an SD card I was also able to mount the image files in Ubuntu however I'm not sure on where to start with trying to make a few implementations for use of the features on the camera as an IP camera only with RTSP. It is a camera that has the PTZ functionality as well as two-way communication and night vision with a spotlight would you have any ideas on where to start with that

**Comment by roleoroleo** [comment]
- Check if the cam is already supported by an existing hack (yi-hack-v5, yi-hack-mstar, yi-hack-allwinner, yi-hack-allwinner-v2, etc...). If it's not a Yi cam, use the fw version (Yi fw version) as a key. As you can see in this page: https://github.com/roleoroleo/yi-hack-Allwinner-v2?tab=readme-ov-file#supported-cameras the hack supports cams from other vendors.
- Open the cam and check the label on the cpu.
- If the model is new and not yet supported, you could start with a new repo cloning an existing project and trying to adapt the code to your model.

**Comment by roleoroleo** [comment]
If you want to share the image, I can take a look at it.
