### ISSUE TITLE
media player

### ISSUE THREAD

**Issue by divemasterjm** [roleoroleo/yi-hack_ha_integration#15]
@roleoroleo can you please put an example and also options we can use in content id and content type?

**Comment by roleoroleo** [comment]
Why do you need to use content id and content type?
Are you using tts or another service?

**Comment by divemasterjm** [comment]
i use tts but didnt work, tried media_player.play_media sending mp3 but sound was slow

**Comment by Cadsters** [comment]
For me it's working great, thanks! 
But is there a way to set the volume?

**Comment by divemasterjm** [comment]
@Cadsters can you please show me code you use?

**Comment by roleoroleo** [comment]
> For me it's working great, thanks!
> But is there a way to set the volume?

No way, sorry.
