### ISSUE TITLE
Integration not compatible with homeassistant 2024.5.0 

### ISSUE THREAD

**Issue by Cadsters** [roleoroleo/yi-hack_ha_integration#150]
After updating to home assistant 2024.5.0 i get this error msg:
`Detected that custom integration 'yi_hack' calls async_create_task from a thread at custom_components/yi_hack/switch.py, line 183: self.hass.async_create_task(. Please report it to the author of the 'yi_hack' custom integration.`

which is caused by [deprecate_add_hass_job](https://developers.home-assistant.io/blog/2024/04/07/deprecate_add_hass_job) and/or [deprecate_async_track_state_change](https://developers.home-assistant.io/blog/2024/04/13/deprecate_async_track_state_change)

**Comment by sippeeey** [comment]
Same Here. Hope it will be fixed.

**Comment by DrGBHindert** [comment]
same here

**Comment by Cadsters** [comment]
Fixed with version 0.5.0!
