### ISSUE TITLE
Media viewer in Home Assistant is broken due to Unknown Error

### ISSUE THREAD

**Issue by MiguelViana7** [roleoroleo/yi-hack_ha_integration#154]
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/146352009/7275738b-e2e0-4e5b-affc-a8b080a817b1)

I've tried the steps in https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/380 to no avail, I've restarted both Home Assistant and the Camera, the motion events are viewable in the Yi-Hack web portal. Camera is running [yi-hack-MStar](https://github.com/roleoroleo/yi-hack-MStar)

**Comment by MiguelViana7** [comment]
Seems like I have this error in my logs

WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'yi_hack' accesses hass.helpers.device_registry. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from device_registry directly at custom_components/yi_hack/media_source.py, line 71: device_registry = self.hass.helpers.device_registry.async_get(self.hass), please create a bug report at https://github.com/roleoroleo/yi-hack_ha_integration/issues

**Comment by adolfonovo** [comment]
Same Here. I tried the suggested workaround without sucess

**Comment by bedson87** [comment]
Same for me. HA 2024.6.3

**Comment by adolfonovo** [comment]
https://github.com/roleoroleo/yi-hack_ha_integration/pull/153/files

Making the changes suggested in that PR. the problems dissapears.

**Comment by MiguelViana7** [comment]
Can confirm that making the changes in the PR fixed my issues as well, thank you for sharing!

**Comment by roleoroleo** [comment]
PR merged.

**Comment by javiges** [comment]
> Puedo confirmar que realizar los cambios en el PR también solucionó mis problemas, ¡gracias por compartir!

Can you explain to me how to make it work? Copy that code into the media_source.py file? Thank you very much for your help, I'm a newbie and I don't know how to fix it.

**Comment by adolfonovo** [comment]
> > Puedo confirmar que realizar los cambios en el PR también solucionó mis problemas, ¡gracias por compartir!
> 
> Can you explain to me how to make it work? Copy that code into the media_source.py file? Thank you very much for your help, I'm a newbie and I don't know how to fix it.

Just change the file in 
https://github.com/roleoroleo/yi-hack_ha_integration/pull/153/files

Change the code in red instead of the code un green. Use Amy extensión for file management in HA.

**Comment by roleoroleo** [comment]
This issue is fixed in 0.5.1
