### ISSUE TITLE
Error - Config flow could not be loaded

### ISSUE THREAD

**Issue by alienatedsec** [roleoroleo/yi-hack_ha_integration#16]
Hi @roleoroleo 

```
(3) Configure device and entities:

Go to Settings -> Integrations
Click "Add Integration" in the lower-right corner
Select "Yi Cam with yi-hack" integration
```

I am trying to follow the instructions, so after the above steps, the following error appears. 

![image](https://user-images.githubusercontent.com/73167064/117565451-3fb94480-b0a9-11eb-9f39-ba4732fa8d62.png)

I am running HA as the container on QNAP with a dedicated config folder.

**Comment by roleoroleo** [comment]
Please read logs in settings page and check if there is an error.

**Comment by alienatedsec** [comment]
I guess there is some dependency missing

```
Logger: homeassistant.setup
Source: setup.py:144
First occurred: 8 May 2021, 7:49:06 (7 occurrences)
Last logged: 10:14:47

Unable to set up dependencies of yi_hack. Setup failed for dependencies: mqtt
```

**Comment by roleoroleo** [comment]
Yes, you need to add mqtt component.

**Comment by alienatedsec** [comment]
> Yes, you need to add mqtt component.
Thanks @roleoroleo 
I possibly need to change the setup as the container version does not allow for add-on installations.

**Comment by roleoroleo** [comment]
I'm using ha in container.
You can add mqtt directly from web page as a standard integration.

**Comment by TH1485** [comment]
i had the same problem, after installing mqtt it worked. Can this dependency be optional if you only use for streaming op?
Also have some other issues.  for the allwinner-v2 (Yi 1080p Home BFUS | 9.0.19* | y21ga): when streaming on the homepage the stream is always lagging behind for a minute, after a while the camera reboots (crashes i think).

**Comment by roleoroleo** [comment]
> i had the same problem, after installing mqtt it worked. Can this dependency be optional if you only use it for streaming?

If you don't use mqtt, there is no reason to use this component.
Simply add a generic ffmpeg cam or an onvif cam if onvif is enabled.
