### ISSUE TITLE
Error opening stream rtsp://****:****@192.168.1.170/ch0_1.h264

### ISSUE THREAD

**Issue by pablitofernandez** [roleoroleo/yi-hack_ha_integration#19]
Hi,

y25ga camera with y25ga_0.2.6 firmware from yi-hack-Allwinner. I have activated only the High profile in RTSP stream but it looks like Home Assistant integration is looking for the Low profile because of the error:

Error opening stream rtsp://****:****@192.168.1.170/**ch0_1.h264**

If I enable BOTH profile in the RTSP stream I can see it correctly.

Thanks.

**Comment by pablitofernandez** [comment]
Some more information, this only happens If I use

`stream:`

in my home assistant configuration. If I dont put the stream option, I can see the feed correctly in the Picture card.

**Comment by roleoroleo** [comment]
I will check it.
