### ISSUE TITLE
Erro when i add rtsp://192.168.1.120/ch0_0.h264 

### ISSUE THREAD

**Issue by wild-run** [roleoroleo/yi-hack_ha_integration#20]
Error when i add rtsp://192.168.1.120/ch0_0.h264, I can only add it like 192.168.1.120 and port 8080 not port 554 for rtsp

**Comment by roleoroleo** [comment]
You need to add only the http access.
The plugin will detect your cam settings and will install the cam.

**Comment by wild-run** [comment]
thanks for answering, first of all congratulate you on your great work, but it use rtsp to see cam in home assitant?

**Comment by roleoroleo** [comment]
Yes, rtsp is the only way to access the video.
