### ISSUE TITLE
Stream Freezes within a Few Seconds

### ISSUE THREAD

**Issue by Indianb0y016** [roleoroleo/yi-hack_ha_integration#21]
As title states, Im having issues with the camera stream in Hass. The integration connects fine (although it fails to get the connection status and times out). I have a feeling that this bears relation to the stream failing. My network is hardwired and the camera has decent wifi connection, so I think it might be related to the integration. Please let me know how I can help provide more info if needed.

Edit: Was finally able to time the error in the log. It says error demuxing stream. Not the slightest clue what that means, but I assume it has something to do with ffmpeg?

Edit2: Completely forgot to note the model camera Im using. Its allwinner V1. Yi cam 1080p. RTSP is set to low quality 

Edit 3: I have two cameras that are the same. One is an older version of allwinner and the other is the latest allwinner version. The one with the older version is streaming through onvif just fine. The other one on latest version that was freezing on the yi-hack integration is ALSO freezing with the onvif integration, so Im starting to believe that it is a camera firmware issue and nothing to do with this integration. Should I leave this open or close it?

**Comment by roleoroleo** [comment]
Leave it open for a week or two.
Maybe other users have the same issue.

**Comment by Indianb0y016** [comment]
Understood. I have been experimenting with the firmware versions for my cameras and found something interesting. I would like to open an issue or post my findings on the respective camera hacks. But I really dont want to bother you with it, since I have found a workaround and it is to use an older firmware.

**Comment by Indianb0y016** [comment]
Okay, I think Ive discovered the problem. The good news is that it has nothing to do with your wonderful hacks and integration. Its actually my web browser. Running arch with firefox and enabled video acceleration. The stream stops and buffers ONLY on the laptop I use. I discovered this when I used my mobile phone to test it, and the stream ran just fine, albeit with a few stutters but it did not outright fail to buffer. What I am failing to understand is that the stream did not fail on this laptop when using camera version 0.2.3. Everything above that failed. 0.2.4 actually failed to load a video in altogether. But on 0.2.5+, its fine on the mobile device. Just not on the laptop. I believe you had changed the way rtsp is streamed from the camera passed 0.2.4 so this might be related somewhat. But again, I must stress, this is NOT the fault of the camera nor the respective software. This is simply down to user factors (video acceleration vaapi on linux). As such, I will be closing this. If anybody else has issues, check across different devices.

**Comment by roleoroleo** [comment]
Which client are you using in the laptop?
I would like to check if I'am able to reproduce the issue.

**Comment by Indianb0y016** [comment]
Sure thing. Is there a way I can give as much info condensed from the firefox "about:support" page? I can tell you that my distro is AnarchyLinux, (TUI Arch install) with the LTS kernel set. 
Firefox 88.0.1 used, with vaapi ffmpeg acceleration enabled with X11 as the protocol. Compositing is using WebRender in order to enable acceleration. I can try to disable it and see if it works in order to test it. Im currently using motioneye passthrough since the mqtt motion detection wasnt working sadly.. (ai detection OFF). So Im just using motioneye in the meantime. Ill let you know what happens

**Comment by roleoroleo** [comment]
Ok, I will start with motioneye.
Why motion detection doesn't work?
