### ISSUE TITLE
Adding this plugin to HACS repository

### ISSUE THREAD

**Issue by SebLz** [roleoroleo/yi-hack_ha_integration#23]
Hello,
I've come accross this great initiative for integrating yi-hack device and HA and I was wondering if there was any plan to integrate this plugin into HACS. It is quite famous in the HA community and allow people to easily find and add non-official plugins to their HA installation. Although the current installation procedure is already quite easy, this would help boosting the popularity of the
 plugin. I'm not an expert but I think the integration into HACS repo is usually not that hard. It is described here:
https://hacs.xyz/docs/publish/start
Thanks again for your amazing work roleoroleo.
EDIT:
Looks like I typed too fast, it's already in HACS :D! (For some strange reason it did not appear directly in my list).

**Comment by roleoroleo** [comment]
> Looks like I typed too fast, it's already in HACS :D! (For some strange reason it did not appear directly in my list).

I didn't integrate this component in HACS.
Where did you see it in HACS?

**Comment by SebLz** [comment]
It's not in the official repo but I could install it adding it as a custom repo:
https://hacs.xyz/docs/faq/custom_repositories/
Not integrated but at least compatible (I noticed the hacs.json file at the root of the folder).
For sure it'd be even better if it was in the official list but that's already quite easy to install it this way.

**Comment by roleoroleo** [comment]
Ok.
I added hacs compatibility with hacs.json and brands.
I didn't add it to the official repo.
Maybe in the future...
