### ISSUE TITLE
No yi_hack integration

### ISSUE THREAD

**Issue by kayo77** [roleoroleo/yi-hack_ha_integration#24]
yi_hack not found on integration list after instalation and reboot.

core-2021.5.5

**Comment by roleoroleo** [comment]
I'm using it with 2021.5.5.
Check if the installation path is ok.

**Comment by kayo77** [comment]
![Screenshot_20210528_210305](https://user-images.githubusercontent.com/28192324/120030840-3fe99780-bff8-11eb-9b6e-49d8d634589a.png)
Path is ok.

**Comment by degrengo1978** [comment]
I have the same problem

**Comment by kayo77** [comment]
Well... after few hours, integration appered in list.

**Comment by degrengo1978** [comment]
The same - now it is showing in the integrations.

**Comment by plumpfen** [comment]
Waiting half a day by now, folder and files are fine, but the integration doesn't show up.
Just keep the System running or rebooting a few times? How is it possible to be suddenly available after some time? Gives me headaches...

**Comment by kayo77** [comment]
Wait another half day…

**Comment by plumpfen** [comment]
still nothing

**Comment by roleoroleo** [comment]
Does the log show the line:
"2021-06-05 17:58:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration yi_hack which has not been tested by Home Assistant. This com ponent might cause stability problems, be sure to disable it if you experience iissues with Home Assistant"

in the first lines?

**Comment by plumpfen** [comment]
Got it working now. It was not enough to create the folders and files. I had to install the repository costum via hacs. Maybe one should add to the install instruction, or I missed it. But I don't think so.

**Comment by brettvan1** [comment]
Hi Roleoroleo:

I have that error message when i tried to load it in.

2021-06-07 11:34:13 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration yi_hack which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by roleoroleo** [comment]
> Got it working now. It was not enough to create the folders and files. I had to install the repository costum via hacs. Maybe one should add to the install instruction, or I missed it. But I don't think so.
> It's quite helpfull for beginners.

I didn't add the hacs installation because I didn't test it.
But I could try to add it.

**Comment by roleoroleo** [comment]
> 
> 
> Hi Roleoroleo:
> 
> I have that error message when i tried to load it in.
> 
> 2021-06-07 11:34:13 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration yi_hack which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

It's normal. HA warns you about a custom installation installed.

**Comment by brettvan1** [comment]
It seemed to have appeared after a day.  Somehow auto discovered?  

Now another problem... Upon integration  install:
"
Error
Config flow could not be loaded"

i tried poking around to see if i could find a fix but wasn't able to...

**Comment by brettvan1** [comment]
was able to get it working.  had to do some trial and error stuff but it works.  When i get a min, i'll try and write up some tips.

**Here was some links that helped:**
https://www.home-assistant.io/integrations/mqtt/
https://www.home-assistant.io/docs/mqtt/broker#run-your-own
https://github.com/home-assistant/addons/blob/master/mosquitto/DOCS.md
https://aarongodfrey.dev/home%20automation/building_a_home_assistant_custom_component_part_3/


I think that I was getting the above error message because I did not have the correct dependency seen in manifest.json: **mqtt**

**Comment by roleoroleo** [comment]
Yes. This component requires mqtt.

**Comment by MarcALE** [comment]
> > Got it working now. It was not enough to create the folders and files. I had to install the repository costum via hacs. Maybe one should add to the install instruction, or I missed it. But I don't think so.
> > It's quite helpfull for beginners.
> 
> I didn't add the hacs installation because I didn't test it.
> But I could try to add it.

HACS install will defintively be great !
