### ISSUE TITLE
Unable to get mac address or serial number from device 

### ISSUE THREAD

**Issue by provaguest** [roleoroleo/yi-hack_ha_integration#25]
I own a Sonoff GK-200MP2B webcam with Sonoff-hack  with IP 192.168.1.161.

After adding the integration, at the first dialog when I try to enter:
- IP: 192.168.1.161
- port: 8080
- username: <the one defined in the sonoff-hack configuration>
- password: <the one defined in the sonoff-hack configuration>
- ffmpeg parameters: -rtsp_transport tcp

my entries are not accepted and a blank form is shown.
In the log of Home Assistant i see:
"Unable to get mac address or serial number from device 192.168.1.161"

IP is correct and the URL http://<username>:<password>@192.168.1.161:8080 is working properly.

Thank you for any advice

**Comment by roleoroleo** [comment]
Which sonof-hack version are you using?
Try to run manually the web service from a browser:
`http://192.168.1.245/cgi-bin/status.json`

**Comment by provaguest** [comment]
I had version 0.0.9 and the web service http://192.168.1.245/cgi-bin/status.json returned a "GET not implemented" error.
After upgrading to 0.1.0 everything was working and the installation completed successfully.
Thanks a lot for the debugging!
