### ISSUE TITLE
yi_hack integration install

### ISSUE THREAD

**Issue by justin00000-cpu** [roleoroleo/yi-hack_ha_integration#26]
Hi there, thank you for all the hard work maintaining this project. I got my camera flashed successfully, and now I am trying to install the custom integration, but I get the same error message over and over after reboot.

The following integrations and platforms could not be set up:
yi_hack
Please check your config and logs.

Log: 
Logger: homeassistant.setup
Source: setup.py:138
First occurred: 20:41:12 (1 occurrences)
Last logged: 20:41:12
Setup failed for yi_hack: No setup function defined.

Also, no entities are created.

What can i do to fix this error?

**Comment by roleoroleo** [comment]
Which version are you using?
Both the hack of the cam and home assistant.

**Comment by justin00000-cpu** [comment]
Home assistant version: 2021.1.5
Cam hack: y21ga
