### ISSUE TITLE
Any way to off/on camera?

### ISSUE THREAD

**Issue by wild-run** [roleoroleo/yi-hack_ha_integration#28]
Any way to off/on camera?

**Comment by roleoroleo** [comment]
If you mean swith on/off the power, it's not possible.

If you mean disable all services like rtsp, onvif, etc... yes.
Except http.
But it's work in progress.

If you mean the same behavior of the switch inside the original app, it's already implemented: first switch in "Camera settings" page.

**Comment by roleoroleo** [comment]
It's work in progress.

**Comment by McGiverGim** [comment]
That is not what the `switch_on` setting of the `camera_settings` web service does?

I used it a lot, with an http request (it is not included in this integration). But it has two problems:
- The first, it disables the video, this is ok, is what we want, but it does not disable the snapshots. I think is better to "disable" all. What we want is a privacy feature disabling any kind of recording.
- The second, Home Assistant complains constantly about camera not available. I don't know if we can "disable" or "stop" the camera entity when the real camera is off.

Is a solution for this what is a work in progres?

Thanks for your great work in advance!!!

**Comment by roleoroleo** [comment]
> 
> 
> That is not what the `switch_on` setting of the `camera_settings` web service does?
> 
> I used it a lot, with an http request (it is not included in this integration). But it has two problems:

This is a complicated question.
The switch_on settings of the camera settings is a clone of the switch you find in the app.
It switch off the stream between the cam and the app but the cam is online and switched on.
This switch doesn't change the behavior of the services added with the hack: snapshot, rtsp, onvif, etc...
So if you don't use the app, this switch has no effect.

The new web service
cgi-bin/service.sh?name=all&action=start
cgi-bin/service.sh?name=all&action=stop
switches on and off the following services: rtsp, onvif, wsdd, ftpd, mqtt and mp4record (recording).

>     * The first, it disables the video, this is ok, is what we want, but it does not disable the snapshots. I think is better to "disable" all. What we want is a privacy feature disabling any kind of recording.

What video and what snapshot? app, rtsp, web?

>     * The second, Home Assistant complains constantly about camera not available. I don't know if we can "disable" or "stop" the camera entity when the real camera is off.

I don't know if this is correct or not.
If you disable all services, the cam should appear on or off?

I improved (but not committed) the components and I added a switch that calls this web service.
But there are 3 different function to turn on/off and I could use them in a different way.
- A general switch (a real ha switch).
- media_player.turn_on
- cam.turn_on

What's the right way to use them?

**Comment by McGiverGim** [comment]
I'm pretty sure that the switch off of the app, disables the rtsp stream. The rest remains enabled.
I think the best way is to use a camera.turn_on service.

**Comment by roleoroleo** [comment]
Which cam?

**Comment by McGiverGim** [comment]
It's a y20ga model  I have used it with the onvif integration and now with yours.

**Comment by robtesch** [comment]
Hi @roleoroleo. First of all, thanks very much for all your work on Yi-Hacks. I see you pushed an update to allow us to "set_privacy".

I've previously just used the "camera_settings.sh" script to turn the cameras on/off. I even made an incredibly basic custom component for HA (which I've only just pushed up to github: https://github.com/robtesch/home-assistant-yi-camera-custom).

I personally feel this is a better approach than turning on/off the "privacy" mode. What are your thoughts?

**Comment by poiedk** [comment]
@robtesch Any guide on how to use this component after installation?

**Comment by robtesch** [comment]
> @robtesch Any guide on how to use this component after installation?

I will do up a quick README asap. I made the component mostly for personal use.

**Comment by robtesch** [comment]
> @robtesch Any guide on how to use this component after installation?

Sorry for the delay here. I've written up a README and also made it installable via HACS as a custom repo.

**Comment by roleoroleo** [comment]
> I personally feel this is a better approach than turning on/off the "privacy" mode. What are your thoughts?

Your approach is correct but it only switches on or off the link between the cam and the yi app.
The privacy switch (or privacy web service, it's the same) also switches rtsp and snapshot.

**Comment by robtesch** [comment]
Thanks @roleoroleo but it actually does turn off the rtsp stream also (at least my HA install can no longer see the stream when the camera is in "off" mode). I am still able to use the media player though. The LED also turms off to indicate it's not recording. I've used this method for several months and it's worked really well for home/away routines.

**Comment by roleoroleo** [comment]
> Thanks @roleoroleo but it actually does turn off the rtsp stream also

Yes, it depends on the model (mstar, allwinner, etc...).
For your model it's the same.

**Comment by robtesch** [comment]
Ah, ok. Got it. Alright thanks. I guess the privacy mode is perhaps more universal then? I will continue to use my mini component for the time being just for off/on.

**Comment by roleoroleo** [comment]
Yes, privacy is "compatible" with many models.
