### ISSUE TITLE
Two cameras linked in the same integration

### ISSUE THREAD

**Issue by cbroissa-github** [roleoroleo/yi-hack_ha_integration#29]
Hello,
I use the h30ga hack for my two Yi Outdoor 1080p IFUS cameras.
I use two differents device name in camera settings (IP:8080)

I add the first one in a new piece, I change the entity name, it's ok.
I add the second in another piece, the two cam are on this same piece, and the two integrations are linked.

There is no problem with my others cam Yi 1080p Home IFUS, there is one integration for each camera.

**Comment by roleoroleo** [comment]
What do you mean with linked?

**Comment by cbroissa-github** [comment]
here is a screenshot, you can see on an entity, there is the two integrations and all others entities.

![IMG_0177](https://user-images.githubusercontent.com/83312047/121480077-fa02db00-c9ca-11eb-8142-5c5a7e42d8d2.jpg)

**Comment by roleoroleo** [comment]
What a weird behavior.
I will check it.

**Comment by xiaopeng12138** [comment]
I have the same issue. Can not separate 2 devices is usable but quite annoying.

**Comment by roleoroleo** [comment]
Did you try the last version?

**Comment by xiaopeng12138** [comment]
> Did you try the last version?

I tried v0.3.1. After I added two cameras it still only shows one device in the list. Is it because 2 cameras have the same username and password?

**Comment by cbroissa-github** [comment]
After update yi-hack firmware of my 4 cam and HA integration firmware to v0.3.1, I have always the problem.

**Comment by roleoroleo** [comment]
Please check if serial number (the one listed in status page) is different.

**Comment by cbroissa-github** [comment]
Yes I have 00000000000000000000 for the 4…
Can I edit it or it’s a bug in the hack ?

**Comment by roleoroleo** [comment]
What's the yi fw version?

**Comment by cbroissa-github** [comment]
0.1.9

**Comment by roleoroleo** [comment]
I mean the version shown in yi app.
9.0.36...

**Comment by roleoroleo** [comment]
But try the last version.
I changed the entry_id from serial number to mac address: it should work.
But you need to remove all cams and add again.

**Comment by cbroissa-github** [comment]
9.0.26.07_202104231123 for 2 cameras
9.0.36.01_202103231716 for 2 cameras 

I will try your last version in a few minutes.

**Comment by cbroissa-github** [comment]
I always have the problem with 0.3.2 version.

**Comment by roleoroleo** [comment]
> 9.0.26.07_202104231123 for 2 cameras
> 9.0.36.01_202103231716 for 2 cameras 
> 

Is the problem related to 9.0.36?
Is the sn 0000000... for all 4 cams?

**Comment by cbroissa-github** [comment]
Yes with 9.0.36 and 9.0.26 too.
All sn are 000000000

**Comment by roleoroleo** [comment]
Sorry but I need more details.
Are the entities linked in pairs?
2 cams with 9.0.36 mixed and 2 cams with 9.0.26 mixed or 4 cams mixed togheter?

**Comment by cbroissa-github** [comment]
All 4 are mixed together

**Comment by roleoroleo** [comment]
Ok, now is fixed.
But I need to fix the serial number detection in the hack to complete the task.

**Comment by cbroissa-github** [comment]
Yes it works, good job !
Thank you.
