### ISSUE TITLE
[Enhancement] Support HACS custom repository

### ISSUE THREAD

**Issue by vin-w** [roleoroleo/yi-hack_ha_integration#3]
Hi!

I think it would be easier if we could add the integration via HACS(Home Assistant Community Store) in HASS to enjoy the upgrade feature via web GUI.

Just follow the git directory structure
https://hacs.xyz/docs/publish/integration/#repository-structure

1. move /yi_hack to /custom_components/yi_hack
2. Create /hacs.json

```
{
    "name": "Yi Cam with yi-hack",
    "render_readme": true
}
```

**Comment by roleoroleo** [comment]
What do you think of my last version?

**Comment by vin-w** [comment]
It's working well! Thank you so much!
I just updated to latest version.
Hope more people will enjoy this integration!
