### ISSUE TITLE
Problem with HA

### ISSUE THREAD

**Issue by kafej** [roleoroleo/yi-hack_ha_integration#30]
Hi,

I have a problem with this awesome plugin. My stream isn't working. Does someone have something similar?
Webrtc shows me an error:

![obraz](https://user-images.githubusercontent.com/1838978/122221049-35ad1180-ceb1-11eb-8458-bdb5205fb550.png)

**Comment by roleoroleo** [comment]
If you try the rtsp stream with vlc, does it work?
Are you using authentication?

**Comment by kafej** [comment]
Yes, I tried with and without authentication and yes it works without flaws in VLC.

**Comment by kafej** [comment]
Oh and in HA rtsp works without problem (on lower stream quality), but this plugin show me only loading indicator...

**Comment by Watanakas** [comment]
Hi friend, you have to use username and password as indicated in the integration, try.

type: 'custom: webrtc-camera'
url: 'rtsp: //user:password@ipcamera:554/ch0_0.h264'

**Comment by kafej** [comment]
> 
> 
> Hi friend, you have to use username and password as indicated in the integration, try.
> 
> type: 'custom: webrtc-camera'
> url: 'rtsp: //user:password@ipcamera:554/ch0_0.h264'

Ok, that help, but I will not use Yi-hack mode then...

**Comment by roleoroleo** [comment]
What kind of ha installation are you using?

**Comment by Watanakas** [comment]
> > Hola amigo, debes usar nombre de usuario y contraseña como se indica en la integración, prueba.
> > escriba: 'custom: webrtc-camera' 
> > url: 'rtsp: //user:password@ipcamera:554/ch0_0.h264'
> 
> Ok, eso ayuda, pero no usaré el modo Yi-hack entonces ...

I am using the Yi Hack application to detect movements and the WebRTC to view on a lovelace card, it has no delay.

**Comment by roleoroleo** [comment]
I mean ha installation like core, docker, raspberry, etc...
Because my docker installation has a similar problem.
The config directory is mounted on a no-exec path.
So the binary rtsp2webrtc_v4_amd64 can't be executed.
I copied it manually to /bin and created a symlink to fix it.

**Comment by PilaScat** [comment]
> I mean ha installation like core, docker, raspberry, etc... Because my docker installation has a similar problem. The config directory is mounted on a no-exec path. So the binary rtsp2webrtc_v4_amd64 can't be executed. I copied it manually to /bin and created a symlink to fix it.

I have the same problem, but webrtc works with other non yi cams, can you make more detailed instruction on how to fix?
