### ISSUE TITLE
PTZ implementations

### ISSUE THREAD

**Issue by ranrinc** [roleoroleo/yi-hack_ha_integration#32]
Hi,

Wondering how do I add PTZ into webRTC implementations? Yes, my yi have PTZ access. Thanks

**Comment by roleoroleo** [comment]
Sorry but webrtc is not my project.
Try to ask to the owner.

**Comment by ranrinc** [comment]
more into what need to be called to perform the PTZ so I can embedded to Home Assistant?

**Comment by ranrinc** [comment]
> ```
> type: custom:webrtc-camera
> url: URL
> title: CAM
> intersection: 0.75
> muted: false
> ui: true
> ptz:
>   service: yi_hack.ptz
>   data_left:
>     entity_id: camera.yi_hack
>     movement: left
>   data_right:
>     entity_id: camera.yi_hack
>     movement: right
>   data_up:
>     entity_id: camera.yi_hack
>     movement: up
>   data_down:
>     entity_id: camera.yi_hack
>     movement: down
> ```

so entity_id will be the name of the camera? If used HA integrations?

Again thanks bro @pszafer
