### ISSUE TITLE
Unable to set up dependencies of yi_hack. Setup failed for dependencies: mqtt

### ISSUE THREAD

**Issue by ilya-shknaj** [roleoroleo/yi-hack_ha_integration#33]
First of all, I would like to say thank you for this integration.
Unfortunately on step "Select "Yi Cam with yi-hack" integration" I see an error and in log I see the following

Logger: homeassistant.setup
Source: setup.py:152
First occurred: 22:44:32 (1 occurrences)
Last logged: 22:44:32

Unable to set up dependencies of yi_hack. Setup failed for dependencies: mqtt

**Comment by roleoroleo** [comment]
Yes, as mentioned in the readme, you need to install mqtt.
