### ISSUE TITLE
Yi Camera Movement (MQTT) and yi-hack-allwinner-v2-xxx_motion_detection don't work on Dome U Pro

### ISSUE THREAD

**Issue by SmartM-ui** [roleoroleo/yi-hack_ha_integration#34]
Hi, 
I can't get motion detection activation displayed on Dome U Pro.

It is always inactive and not even the image of the detected movement is reported (camera.yi_hack_allwinner_v2_xxx_motion_detection_cam)

I tried disabling AI Human Detection from the YIHACK control panel, but it still doesn't detect motion.

Which setting should I activate?

Thanks

**Comment by roleoroleo** [comment]
Ok detection cam doesn't work.
But are you able to receive the mqtt message?
And can you see the event on your yi app?

**Comment by SmartM-ui** [comment]
Surely on the YI app it detects motion, AI Human detects and Facial detection.
Tomorrow I disable the AI Human Detector from your YIHACK and monitor the MQTT data that passes through.
