### ISSUE TITLE
Image detected by the AI Human Detection sensor

### ISSUE THREAD

**Issue by SmartM-ui** [roleoroleo/yi-hack_ha_integration#36]
It would be possible to view the image saved to the movement of the AI Human Detection sensor (e.g. camera.yi_hack_allwinner_v2_xxx_motion_ai_human_detection_cam)

Thank you

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/209#issuecomment-874303807

**Comment by SmartM-ui** [comment]
Sorry if I duplicated the post, I saw after that there was the section for Home Assistant.

Thanks again for everything.
