### ISSUE TITLE
YIapp "At home" and "Away" modes controlled by Home Assistant / YIHack

### ISSUE THREAD

**Issue by SmartM-ui** [roleoroleo/yi-hack_ha_integration#37]
Hi,
There is a way, through integration, sensor, MQTT, to send the command "at home" and "not_home" from Home Assistant and have it read to the YI app. It would be handy for creating automations.
I have noticed that the commands that are sent via integration / MQTT are executed, but are not synchronized by HA / YIapp.
Example, if I activate the cam from YIapp, the switch on Home Assistant continues to be disabled
Thanks

**Comment by roleoroleo** [comment]
> There is a way, through integration, sensor, MQTT, to send the command "at home" and "not_home" from Home Assistant and have it read to the YI app. It would be handy for creating automations.

We need to check if the app sends a message to the cam when you toggle this switch.
Capture it and send it to the cam when you want.

> I have noticed that the commands that are sent via integration / MQTT are executed, but are not synchronized by HA / YIapp.
> Example, if I activate the cam from YIapp, the switch on Home Assistant continues to be disabled

I was unable to reverse the configuration file in the cam.
I can't read and write how the cam is configured.
So I saved this settings to a different file and the result is that app and web site are not synchronized.

**Comment by SmartM-ui** [comment]
> > There is a way, through integration, sensor, MQTT, to send the command "at home" and "not_home" from Home Assistant and have it read to the YI app. It would be handy for creating automations.
> 
> We need to check if the app sends a message to the cam when you toggle this switch.
> Capture it and send it to the cam when you want.
> 
> > I have noticed that the commands that are sent via integration / MQTT are executed, but are not synchronized by HA / YIapp.
> > Example, if I activate the cam from YIapp, the switch on Home Assistant continues to be disabled
> 
> I was unable to reverse the configuration file in the cam.
> I can't read and write how the cam is configured.
> So I saved these settings to a different file and the result is that app and web site are not synchronized.

Do I always capture the data via IPC_Sniff?

Thanks again and sorry for all my requests, but you are the only one who could be able to make the YI better!

I bought it only knowing that there was your YIHACK :-)

**Comment by roleoroleo** [comment]
Yes, use ipc_sniff.

**Comment by SmartM-ui** [comment]
Hi @roleoroleo 
this is the data that is detected when I press the Home and Not_Home button from the YIhome app

![Screenshot_20210707-152636_YI Home](https://user-images.githubusercontent.com/63554131/124768088-aab3ba00-df38-11eb-98ed-0bc9e1c98c63.jpg)

Not_Home:
IPC message. Len: 20. Status: No error information!
Parsing message.
01 00 00 00 04 00 00 00 8e 00 01 00 04 00 00 00 00 dd 6d 00

Home:
IPC message. Len: 20. Status: No error information!
Parsing message.
01 00 00 00 04 00 00 00 8e 00 01 00 04 00 00 00 00 dd 6d 00

I hope it can be used for the switch and synchronization with Home Assistant

**Comment by roleoroleo** [comment]
This is strange, it's the same message.

**Comment by SmartM-ui** [comment]
Hi,
I wanted to try to run the command again to verify the correctness of the data reported, but when I try to change mode in Not_Home, this error is reported:

IPC message. Len: 16. Status: No error information!
Parsing message.
01 00 00 00 02 00 00 00 7c 00 7c 00 00 00 00 00 
Sending MOTION_START to queue #1
Sending MOTION_START to queue #2
Sending MOTION_START to queue #3
Sending MOTION_START to queue #4
Sending MOTION_START to queue #5
Sending MOTION_START to queue #6
Sending MOTION_START to queue #7
Sending MOTION_START to queue #8
Sending MOTION_START to queue #9
IPC message. Len: 16. Status: Resource temporarily unavailable!
Parsing message.
01 00 00 00 08 00 00 00 81 00 01 00 00 00 00 00 
IPC message. Len: 16. Status: Resource temporarily unavailable!
Parsing message.
01 00 00 00 02 00 00 00 f6 00 f6 00 00 00 00 00 
IPC message. Len: 16. Status: Resource temporarily unavailable!
Parsing message.

**Comment by roleoroleo** [comment]
This is not an error. It's ok.

**Comment by SmartM-ui** [comment]
> This is not an error. It's ok.

OK,
however, it no longer shows the data it reported yesterday:
01 00 00 00 04 00 00 00 8e 00 01 00 04 00 00 00 00 dd 6d 00

**Comment by roleoroleo** [comment]
I think the "Home/Away" switch is cloud side only.
It probably doesn't affect the cam settings but only the app.

**Comment by SmartM-ui** [comment]
> I think the "Home/Away" switch is cloud side only.
> It probably doesn't affect the cam settings but only the app.

But yesterday when I pressed the home not_home from button, your sniffer received that data: 
01 00 00 00 04 00 00 00 8e 00 01 00 04 00 00 00 00 dd 6d 00

today he receives nothing.
After I try again

**Comment by roleoroleo** [comment]
There are a lot messages between the processes.
Maybe the sniffer caught another one that has nothing to do with Home/Away.
