### ISSUE TITLE
error setting up integration

### ISSUE THREAD

**Issue by divemasterjm** [roleoroleo/yi-hack_ha_integration#4]
Hi, after install and copy the integration ive got the following error
latest frimware h201

Error setting up entry yi-hack-6023a403226e for yi_hack
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/yi_hack/__init__.py", line 48, in async_setup_entry
    hass.config_entries.async_update_entry(entry, data={**entry.data, CONF_TOPIC_AI_HUMAN_DETECTION: mqtt[CONF_TOPIC_AI_HUMAN_DETECTION]})
KeyError: 'TOPIC_AI_HUMAN_DETECTION'

**Comment by divemasterjm** [comment]
i comment the lines refering to ai and sound detection and is working

**Comment by roleoroleo** [comment]
I will check it.
Thanks.

**Comment by divemasterjm** [comment]
thanks, if you need test or more info just tell me

**Comment by roleoroleo** [comment]
Fixed.
Try version 0.2.6

**Comment by divemasterjm** [comment]
done, and works!!!
thanks
