### ISSUE TITLE
How to configure mqtt binary sensors?

### ISSUE THREAD

**Issue by iMrLopez** [roleoroleo/yi-hack_ha_integration#40]
How can I configure the binary sensors to match my mqtt topics?

I made my own topics from my camera, they look like `cams/<cam>/motion_detected` and so on... and need to configure the binary sensors created by this integration, but cannot find any example anywhere on how to do it

**Comment by roleoroleo** [comment]
Binary sensors are automatically created by the integration.

**Comment by iMrLopez** [comment]
@roleoroleo I know, but mine are not working, I think is because I published my mqtt to a custom topic, which I have not set anywhere in the integration

**Comment by roleoroleo** [comment]
The topics are automatically detected by the integration.
When it connects to the cam, it gets the configurations and reads the topics.
Is mqtt integration enabled in your ha?
