### ISSUE TITLE
MQTT motion_detection_image (null)

### ISSUE THREAD

**Issue by pl4za** [roleoroleo/yi-hack_ha_integration#42]
This topic seems to return a null payload, every other topic works fine.

![image](https://user-images.githubusercontent.com/9530588/127024995-e67818ff-4925-4440-b765-e894969686dd.png)

**Comment by roleoroleo** [comment]
I will check it.

**Comment by roleoroleo** [comment]
Is this error still present?

**Comment by bluehz** [comment]
Yes still present

**Comment by roleoroleo** [comment]
Which cam model and which suffix?

**Comment by bluehz** [comment]
yi home 27US

**Comment by roleoroleo** [comment]
Sorry, but I think that the problem is the cam, not the integration.
Try to read the message with MQTT Explorer.
If it's empty, open a issue in the repo of the hack.
