### ISSUE TITLE
Can't add 720p cam

### ISSUE THREAD

**Issue by areyoufserious** [roleoroleo/yi-hack_ha_integration#43]
Hi. I use https://github.com/TheCrypt0/yi-hack-v4 for 720p yi cam
i can't add it in integration, page just reload
can you help me?

https://github.com/roleoroleo/yi-hack_ha_integration

btw I added to integration another yi-hacks for my 1080 yi cams

**Comment by roleoroleo** [comment]
yi-hack-v4 is not supported.
