### ISSUE TITLE
GK-200MP2B PTZ issue

### ISSUE THREAD

**Issue by blazejp83** [roleoroleo/yi-hack_ha_integration#44]
So I was able to connect the Sonoff cam, model GK-200MP2B, using the hacked firmware. Using your component I can see 5 entities in the HA (cam, motion detection, motion detection cam, privacy, status). The question is, how to get the PTZ controls? Are they somehow implemented? Or should I try some other approach, like WebRTC and Sonoff LAN?

**Comment by roleoroleo** [comment]
ptz is a service.
You can try it in "Developer Tools" -> "Services".
