### ISSUE TITLE
2021.9 camera width and height issue

### ISSUE THREAD

**Issue by andriej** [roleoroleo/yi-hack_ha_integration#45]
Since 2021.9 there has been change in camera domain, which causes warning in log thrown for this integration:
`The camera entity camera.garage does not support requesting width and height, please open an issue with the integration author`

![image](https://user-images.githubusercontent.com/6303489/131744781-6984c6b9-d34e-461e-b237-e36f2bd23b46.png)
https://www.home-assistant.io/blog/2021/09/01/release-20219/

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack_ha_integration/commit/0a8664bedb397785605f68d0c1f04cabb89232ca

**Comment by andriej** [comment]
Thx :)
