### ISSUE TITLE
Home Assistant complains against width and height support

### ISSUE THREAD

**Issue by McGiverGim** [roleoroleo/yi-hack_ha_integration#47]
I have this warning in the Home Assistant logs:
```log
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:465
Integration: Cámara (documentation, issues)
First occurred: 2 de septiembre de 2021 15:14:38 (2 occurrences)
Last logged: 8:03:10

The camera entity camera.pasillo does not support requesting width and height, please open an issue with the integration author
The camera entity camera.camara_pasillo_movimiento_camara does not support requesting width and height, please open an issue with the integration author
```
I think this is related with the new version 2021.9.0:
> Thanks to @bdraco, camera images can now be scaled to a resolution that fits the device/screen you are looking at; Additionally, they only update when visible. This makes cameras usable in any bandwidth situation.

**Comment by roleoroleo** [comment]
See this:
https://github.com/roleoroleo/yi-hack_ha_integration/issues/45

**Comment by McGiverGim** [comment]
Thanks! I don't know how I didn't find it...
