### ISSUE TITLE
Privacy sensor detached from camera

### ISSUE THREAD

**Issue by McGiverGim** [roleoroleo/yi-hack_ha_integration#49]
This is a strange issue. In the latest update of the integration, the new privacy sensor appeared (great) but for some reason it is not "attached" to the device.

I will try to explain it better with images.

The integration has one device and nine sensors (that's ok):
![image](https://user-images.githubusercontent.com/2673520/133391624-cf02c103-6084-4a80-a81d-1617e6a4b78b.png)

If I select the device, it shows the sensors attached to the device, it only shows eight sensors, the privacy one isn't there:
![image](https://user-images.githubusercontent.com/2673520/133391763-9ddf1cdb-c35b-4c49-befa-30622a0adaf1.png)

If I filter for the sensors related with the integration, the privacy sensor is there, there are nine sensors:
![image](https://user-images.githubusercontent.com/2673520/133391519-e94ffdfc-c932-4011-8f8b-5be05df9a7fa.png)

**Comment by roleoroleo** [comment]
Try the last commit.

**Comment by McGiverGim** [comment]
Seems to be working, thanks!!

![image](https://user-images.githubusercontent.com/2673520/133561996-bbad7c4a-ab25-44d6-b976-05c3fe8b690d.png)
