### ISSUE TITLE
Can't add integration

### ISSUE THREAD

**Issue by marithpl** [roleoroleo/yi-hack_ha_integration#53]
I followed instructions of install of this component.
When I trying to fill a form with Yi Camera data (address, port, login, password) I received an:
"User input malformed"

**Comment by roleoroleo** [comment]
Please, explain me better.

**Comment by marithpl** [comment]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/25366097/140387040-6cc50b39-b732-443f-a12a-34a01d91b052.png">

**Comment by marithpl** [comment]
I found a workaround.
I rollback to 2021.10.6 after that connected with integration with no issue.

**Comment by roleoroleo** [comment]
Do you want to try this commit?
https://github.com/roleoroleo/yi-hack_ha_integration/commit/c15ca3d931d468034c54a91fbc2af71886f213cc

**Comment by timknowlden** [comment]
I have the same issue, how do I try that commit?

**Comment by roleoroleo** [comment]
You can edit the files as described in the commit or download again the repo.
