### ISSUE TITLE
Integration not discovering movment

### ISSUE THREAD

**Issue by Vormillion** [roleoroleo/yi-hack_ha_integration#54]
Hi,

I installed this integration in HA (latest hassio) and after login I have new entities available. Unfortunately motion sensor is not working at all - it's always showing no movment.

I sshed into camera and execute mqttv4 and I can see MQTT events for motion_detection without any issue.

CALLBACK MOTION START
Client yi-cam sending PUBLISH (d0, q1, r1, m2, 'yicam/motion_detection', ... (12 bytes))
Starting program
Mapping file /dev/shm/fshare_frame_buf, size 1786156, to b6da5000
Decoding h264 frame
Starting decode
Decode frame
Client yi-cam received PUBACK (Mid: 2)
Writing yuv buffer
Cleaning ffmpeg memory
Adding watermark
Encoding jpeg image
Unmapping file /dev/shm/fshare_frame_buf, size 1786156, from b6da5000
Client yi-cam sending PUBLISH (d0, q1, r1, m3, 'yicam/motion_detection_image', ... (234533 bytes))
Client yi-cam received PUBACK (Mid: 3)
CALLBACK MOTION STOP
Client yi-cam sending PUBLISH (d0, q1, r1, m4, 'yicam/motion_detection', ... (11 bytes))
Client yi-cam received PUBACK (Mid: 4)
CALLBACK MOTION START
Client yi-cam sending PUBLISH (d0, q1, r1, m5, 'yicam/motion_detection', ... (12 bytes))
Starting program
Mapping file /dev/shm/fshare_frame_buf, size 1786156, to b6d72000
Decoding h264 frame
Starting decode
Decode frame
Writing yuv buffer
Client yi-cam received PUBACK (Mid: 5)
Cleaning ffmpeg memory
Adding watermark
Encoding jpeg image
Unmapping file /dev/shm/fshare_frame_buf, size 1786156, from b6d72000
Client yi-cam sending PUBLISH (d0, q1, r1, m6, 'yicam/motion_detection_image', ... (234377 bytes))
Client yi-cam received PUBACK (Mid: 6)
CALLBACK MOTION STOP

**Comment by roleoroleo** [comment]
Check if your mqtt server receives the messages.

**Comment by Vormillion** [comment]
Yes, I checked on HA:

mosquitto_sub -h 192.168.1.214  -p 1883 -v -d -q 1 -t 'yicam/motion_detection'

and I'm getting messages

**Comment by Vormillion** [comment]
Hmm, I just checked again and getting:

[core-ssh config]$ mosquitto_sub -h 192.168.1.214  -p 1883 -v -d -q 1 -t 'yicam/motion_detection'
Client (null) sending CONNECT
Client (null) received CONNACK (0)
Client (null) sending SUBSCRIBE (Mid: 1, Topic: yicam/motion_detection, QoS: 1, Options: 0x00)
Client (null) received SUBACK
Subscribed (mid: 1): 128
Client (null) sending DISCONNECT
All subscription requests were denied.

**Comment by xinux87** [comment]
I'm having similar problem, with 5  cameras. I can see the MQTTP packets on HO, but it don't refresh the sensors on HA.
![image](https://user-images.githubusercontent.com/6419184/140551202-e727020e-8a34-4832-a95e-6e587e91d669.png)

I have tried to configure first the mqttp on the cameras and later add them in the integration but nothing, but i'm getting the connect status to work.
![image](https://user-images.githubusercontent.com/6419184/140551153-4229b1fb-4eb4-4437-a001-949434c6af6a.png)

Even i've tried to use a diferent Topics Prefix for each camera.

P.d image works fine! but any other sensor than the offline don't work.

Thanks Again!!

**Comment by Vormillion** [comment]
I have even more weird scenario.

Whenever I will reboot camera, mqttv4 is saying that it's connected but HA can't see any messages - sensors are in unavailable status. Sometimes restart of mqttv4 helps, sometimes not. 

I'm still trying to reproduce this issue and see what will help.

**Comment by roleoroleo** [comment]
Please, give me details.
Model suffix and fw of the cam?
Version of the integration?
