### ISSUE TITLE
Motion detection on MQTTP but not appearing in the motion_sensor in HA

### ISSUE THREAD

**Issue by xinux87** [roleoroleo/yi-hack_ha_integration#55]
HI, 

I'm having aproblem, with 5 cameras and the motion_sensor. I can see the MQTTP packets on HO, but it don't refresh the sensors on HA.

![![image](https://user-images.githubusercontent.com/6419184/140622839-af5e59bb-14f9-4094-aac0-a5dcf444be87.png)](https://user-images.githubusercontent.com/6419184/140622833-37b0a8ed-9672-4920-ad48-c81dd80d2229.png)

I have tried to configure first the mqttp on the cameras and later add them in the integration but nothing, but i'm getting the connect status to work.
![image](https://user-images.githubusercontent.com/6419184/140622839-af5e59bb-14f9-4094-aac0-a5dcf444be87.png)

Even i've tried to use a diferent Topics Prefix for each camera.

P.d  works fine! but any other sensor than the offline don't work.

This camera is

Thanks Again!!

**Comment by roleoroleo** [comment]
Which HA version are you using?

**Comment by xinux87** [comment]
Home Assistant 2021.11.2

**Comment by roleoroleo** [comment]
Tested with this version.
It seems working.
Try to disable human detection.

**Comment by xinux87** [comment]
already done and it doen't work, it can be for the CAM? they're using yi-hack-v5.

**Comment by roleoroleo** [comment]
Maybe.
Which version are you using?
Is there any useful log in ha?

**Comment by xinux87** [comment]
Here you have!!

Thanks!!

Firmware Version | 0.4.3
Base Version | 4.2.0.0H_201909041620
Model Suffix | y25


Just This one.

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/yi_hack/common.py:193
Integration: Yi Cam with yi-hack (documentation)
First occurred: November 23, 2021, 1:17:12 AM (50 occurrences)
Last logged: 9:37:57 AM

Update for switch.yi_hack_m_ced657_privacy fails
Update for switch.yi_hack_m_5480ef_privacy fails
Update for switch.yi_hack_m_549b12_privacy fails
Update for switch.yi_hack_m_54975d_privacy fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/yi_hack/switch.py", line 43, in update
    self._state = get_privacy(self.hass, self._device_name, conf)
  File "/config/custom_components/yi_hack/common.py", line 193, in get_privacy
    if response is not None:
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by Burbacottero** [comment]
Same problem here but with allwinner v2.
Home Assistant detection says connected but the sensor doesn't work.

Mosquitto broker logs:
1638136813: New connection from 172.30.32.2 on port 1883.
1638136813: Socket error on client <unknown>, disconnecting.

**Comment by xinux87** [comment]
@roleoroleo There is any place with a tutorial to integrate the cams with the MQTTP?

I mean, it says just need to add the integration and add the IP/Username/password, but we need to add the MQTTP credentials right?? or with the Hack its not necessary¿ 

And anything else?

Like, giving a new name for each camera on the MQTTP section and i dont know...

Thanks!!

**Comment by roleoroleo** [comment]
@xinux87 
Which version are you using?
Line 193 in common.py is blank.

About MQTT, you have to configure credentials:
- when you configure the cam (webpage of the cam).
- when you add MQTT integration in ha.

You don't need to insert username/password when you add this integration.

**Comment by xinux87** [comment]
lol 0.3.1 updating and testing.

**Comment by xinux87** [comment]
Then, in the MQTT webpage from the cam:
/index.html?page=mqtt -> Add server data, and port, then the autentification -> I'm getting the status Connected.
And in the:
index.html?page=mqtt_adv

What do we need to activate everything? with Enabled And Start on boot?

- MQTT Information Advertise
- MQTT Link Advertise
- MQTT Camera Settings Advertise
- MQTT Telemetry Advertise
- Home Assistant -> Changing device ID right?

Or there is a minimal install.

Thanks for your time!

**Comment by xinux87** [comment]
Started Again with the new version.

now i see the motion events on mqtt but, but just motion_stop not motion_start

getting data on the MQTT:
![image](https://user-images.githubusercontent.com/6419184/143872936-997f00f5-18a1-4a75-905d-336eb833d506.png)

Can it be a problem with the firmware of the camera? even i can see the recorded videos, but the event motion_start, dont appears on the mqtt.

![image](https://user-images.githubusercontent.com/6419184/143873528-5e3a12dd-93b6-49d6-bdde-860b9fe28522.png)

added some infor of the webcam:
![image](https://user-images.githubusercontent.com/6419184/143873998-6a91b852-f8a3-4e3b-85a3-7001ffdc3e8e.png)

**Comment by roleoroleo** [comment]
> What do we need to activate everything? with Enabled And Start on boot?
> 
>     * MQTT Information Advertise
> 
>     * MQTT Link Advertise
> 
>     * MQTT Camera Settings Advertise
> 
>     * MQTT Telemetry Advertise
> 
>     * Home Assistant -> Changing device ID right?
> 
> 

If you use this integration, you don't need to activate mqtt advertising.

> Can it be a problem with the firmware of the camera? even i can see the recorded videos, but the event motion_start, dont appears on the mqtt.

Normally this happens if you enable human detection.
But depends on the model.

**Comment by xinux87** [comment]
Afrter some debuggind and help, it seems to be a problem with the firmware that don't send the motion_start via MQTTP.

I will open, in the firmware the issue.

Thanks!!

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack_ha_integration/issues/55#issuecomment-968316266
