### ISSUE TITLE
Not working with yi-hack-v5

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack_ha_integration#56]
![image](https://user-images.githubusercontent.com/12989749/141771679-5e513817-fbfb-42ff-8340-2cd48f21ac70.png)
This with yi-hack v5, with allwinner v2 it works

**Comment by roleoroleo** [comment]
Try to update the component.
I removed CONF_AI_HUMAN_DETECTION_START_MSG.

**Comment by PilaScat** [comment]
I don't see the release

**Comment by roleoroleo** [comment]
Saved release 0.3.4 now.
