### ISSUE TITLE
User input malformed

### ISSUE THREAD

**Issue by AaronAutomation** [roleoroleo/yi-hack_ha_integration#59]
Data via the integration was showing as 'unavailable' for one of my cameras, but one of my others is fine. I rebooted camera, checked MQTT topics and everything looked fine. I deleted and re-added the integration but once entering the camera info I get the error 'User input malformed'. Same error when trying to re-add other camera also.

**Comment by roleoroleo** [comment]
This bug appeared whit ha 2021.11.
But it should be fixed with 0.3.4:
https://github.com/roleoroleo/yi-hack_ha_integration/commit/c15ca3d931d468034c54a91fbc2af71886f213cc

**Comment by AaronAutomation** [comment]
Resolved with manual update to files, ty!
