### ISSUE TITLE
Yi Dome 1080p PTZ entity not created

### ISSUE THREAD

**Issue by sakara** [roleoroleo/yi-hack_ha_integration#6]
Hi i have a Yi Dome 1080p but PTZ entities is not created by the integration

**Comment by roleoroleo** [comment]
What's your model suffix?

**Comment by sakara** [comment]
Firmware Version | 0.4.0
Base Version | 4.6.0.0A_201908271549
Model Suffix | h201c
Serial Number | BFUS*

**Comment by roleoroleo** [comment]
Please wait for the next fw release.

**Comment by roleoroleo** [comment]
Here it is:
https://github.com/roleoroleo/yi-hack-MStar/releases/tag/0.4.1

**Comment by sakara** [comment]
Same problem, no change... only 5 entities found and no PTZ.

**Comment by roleoroleo** [comment]
Post the output of the status command:
`http://IP_CAM:8080/cgi-bin/status.json`

**Comment by sakara** [comment]
{
"name": "yi-hack-mstar",
"hostname": "yi-cam-360",
"fw_version": "0.4.1",
"home_version": "4.6.0.0A_201908271549",
"model_suffix": "h201c",
"ptz": "yes",
"serial_number": "BFUSY1ETFSFF51200310",
"local_time": "Tue Apr 27 15:59:40 CEST 2021",
"uptime": "1768.18",
"load_avg": "4.82 4.80 3.86",
"total_memory": "60856",
"free_memory": "16740",
"free_sd": "100%",
"local_ip": "192.168.1.46",
"netmask": "255.255.255.0",
"gateway": "192.168.1.1",
"mac_addr": "EC:9C:32:CE:59:FB",
"wlan_essid": "sakaranet2G",
"wlan_strength": "79"
}

**Comment by roleoroleo** [comment]
status is ok.
5 entities is correct: 2 cams and 3 binary sensors.
Did you try if ptz service exists?

**Comment by sakara** [comment]
It works! Thank you
