### ISSUE TITLE
MQTT integration not working

### ISSUE THREAD

**Issue by jfsaturos** [roleoroleo/yi-hack_ha_integration#61]
Hi, I trying to configure the MQTT integration with homeassistant but I am not be able to run it correctly. 

I am using yi-hack-Allwinner-v2 y211ga with Yi home IFUS version 9.0.36.02_202105081647. Home assistant version-> 2021.11.5

I have the options Disable Cloud, Recording without Cloud and all the MQTT options enabled. 

But when I add the camera to home assistant I have the following entities:

  - binary_sensor.yi_hack_a2_dc0711_baby_crying-> not working
  - binary_sensor.yi_hack_a2_dc0711_motion_detection-> not working
  - binary_sensor.yi_hack_a2_dc0711_sound_detection-> not working
  - binary_sensor.yi_hack_a2_dc0711_status -> working fine I can see the camera online
  - camera.yi_hack_a2_dc0711_motion_detection_cam -> not working
  - camera.yi_hack_a2_dc0711_cam -> This working fine I can see the images there
  - switch.yi_hack_a2_dc0711_privacy -> Working fine

Could you help me for configure the motion detection properly?, I am interested on the motion detection picture and binary sensor.

Thank you in advance

**Comment by roleoroleo** [comment]
Did you install the mqtt server in ha?
If yes, download a client software (for example MQTT Explorer in Windows) and connect to the mqtt server.
And check it the server receives messages from the cam.

**Comment by jfsaturos** [comment]
Yes I have a mosquito broker configured in order to use zigbee2mqtt.

I downloaded the program and conect to home asssitant. There the camera appears but the variable motion detection appear as -> motion_detection = motion_stop and the value not change 

See picture below
![Test](https://user-images.githubusercontent.com/58632759/142896868-846f821d-2969-4dda-bad0-870e9f700614.JPG)

**Comment by roleoroleo** [comment]
Is human detection enabled?
If yes, try to disable it.

**Comment by jfsaturos** [comment]
Now is working, i disabled the option AI Human Detection | Enable/disable AI Human Detection.

There was the problem. 

Thank you!
