### ISSUE TITLE
Mixing camera snapshot

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack_ha_integration#62]
I have two allwinner v2, in hassio they are set perfectly but the entrance snapshot cam shows the gate snapshot, like duplicated, but streams and motion detection works fine
![image](https://user-images.githubusercontent.com/12989749/143662968-226035d0-31f9-405e-8b46-6f36e12bc1a8.png)
![image](https://user-images.githubusercontent.com/12989749/143663001-24805ab1-c588-4fc5-b758-4cac9a55e345.png)
two devices but same snapshot cam, what

**Comment by roleoroleo** [comment]
I already fixed this problem here: https://github.com/roleoroleo/yi-hack_ha_integration/commit/2508337ba5c270373d08547845495c8ac02ddb9e
What version are you using?
Check the list of the entities in the device:
Settings -> Integrations -> yi_hack_a2_xxxxxx -> device
Are they correctly assigned to the proper device?

**Comment by PilaScat** [comment]
Changed the device name, but I resetted the integration yesterday

**Comment by PilaScat** [comment]
![image](https://user-images.githubusercontent.com/12989749/143858650-6c22029c-9970-4797-a050-2497ce32bfd3.png)
Ti scrivo in italiano così ci capiamo meglio, ho tolto l'integrazione per tutte le telecamere, poi ho rimesso solo quella affetta dal problema, e ora mi fa così 😭

**Comment by roleoroleo** [comment]
Non capisco dov'è l'anomalia nella schermata che hai postato.
Mi sembra tutto ok.

**Comment by Burbacottero** [comment]
> 

Ora e' risolto il problema mio del MQTT ma, avendo 6 telecamere con yi hack allwinnerv2, sia per quanto riguarda il motion detection che il motion detection cam, mi mostra sempre l'ultimo in ogni telecamera.

**Comment by roleoroleo** [comment]
Verificate di aver usato un topic prefix differente per ogni camera.
Anche il client id deve essere diverso.

**Comment by Burbacottero** [comment]
Avevamo modificato entrambi solo il client id e non il topic prefix.
Ora funziona.
Grazie mille😉

**Comment by PilaScat** [comment]
> Verificate di aver usato un topic prefix differente per ogni camera. Anche il client id deve essere diverso.

Ci avevo pensato ma volevo sentire un tuo parere prima di fare casino, grazie
