### ISSUE TITLE
error Could not parse JSON content: /config/custom_components/yi_hack/translations/es.json

### ISSUE THREAD

**Issue by JoseCarlos-Balan** [roleoroleo/yi-hack_ha_integration#64]
i have this error after install 

Logger: homeassistant.util.json
Source: util/json.py:32
First occurred: 22:00:12 (2 occurrences)
Last logged: 22:02:25

Could not parse JSON content: /config/custom_components/yi_hack/translations/es.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 32, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 166: invalid continuation byte

**Comment by roleoroleo** [comment]
It's an error related to utf.
But it should be already fixed in the last commit.
https://github.com/roleoroleo/yi-hack_ha_integration/commit/7bc8787fd73e84528cc950f4451fc6b56424227d
https://github.com/roleoroleo/yi-hack_ha_integration/commit/0cf2fee86e7567e66609dfa2e4ec08f60436505c
