### ISSUE TITLE
[FEATURE REQUEST] Snapshot delay

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack_ha_integration#65]
È possibile aggiungere un delay personalizzabile per la snapshot cam?
Perché è troppo veloce a farlo (tipo appena vede un piede passare) e nello screen non viene mai il soggetto, se potessi ritardarlo di 1/2 secondi sarebbe perfetto, potrei comunque farlo con la cam, ma probabilmente ci sarebbe molto più ritardo visto che non ha il WebRTC integrato, e in più non vorrei rendere obsoleta una funzione che ci sta
Grazie

**Comment by KennyDizi** [comment]
fuck 😂 don't understand

**Comment by roleoroleo** [comment]
This feature depends on the cam and not on the integration.
Please open a new issue in the repo "yi-hack" according to your model.
I could add a "delay" parameter in the mqtt configuration page.

**Comment by PilaScat** [comment]
> This feature depends on the cam and not on the integration. Please open a new issue in the repo "yi-hack" according to your model. I could add a "delay" parameter in the mqtt configuration page.

Ah ok didn't know
