### ISSUE TITLE
HTTP requests

### ISSUE THREAD

**Issue by JanGonet** [roleoroleo/yi-hack_ha_integration#69]
Hi @roleoroleo,

Do you happen to have a list of all parameters that can be changed using http requests, like you suggested in another issue?

Example:
`http://IP-CAM:8080/cgi-bin/camera_settings.sh?ai_human_detection=yes`

I would like to change a few other settings, however I am not able to find the right parameter names - I only discovered that "rotate=yes/no" works. I would be particularly interested in options like enable/disable cloud, enable/disable recording without cloud or status LED.

Cheers!

**Comment by JanGonet** [comment]
Okay, I just discovered that you can get some of those commands via developer tools in Chrome, but this doesn't work for Configurations tab (and these require a reboot), so could you just confirm if this is possible at all, please?

**Comment by roleoroleo** [comment]
Check the wiki.
