### ISSUE TITLE
Status always appears offline

### ISSUE THREAD

**Issue by LeidenSpain** [roleoroleo/yi-hack_ha_integration#70]
First of all, very good work with the component, the truth is that it is going very well.

Likewise, I have encountered a problem that I have not been able to solve:
I have 4 cameras: 1 Yi 1080p with yi-hach 0.4.3, and 3 Yi Outdoor with yi-hack-v5 0.3.2.

The strange thing is that 1080p and one Outdoor detect them online without problems, but 2 outdoor appear offline, although I can see their image.
What can happen?

**Comment by roleoroleo** [comment]
Which firmware?
v5 is not under my control, I try to mantain at the same level of mstar and allwinners but it's not always possible.

**Comment by LeidenSpain** [comment]
> Which firmware? All outdoor have the same v5 firmware? v5 is not under my control, I try to mantain at the same level of mstar and allwinners but it's not always possible.

yes, all Yi Outdoor cameras have the same firmware: 0.3.2

Camera 1 - 4CUS version: STATUS OFFLINE
Camera 2 - ???? version:  STATUS ONLINE
Camera 3 - 4CUS version: STATUS OFFLINE

**Comment by roleoroleo** [comment]
Status sensor is the value of the topic "Birth and will messages".
Did you configure it properly?

**Comment by LeidenSpain** [comment]
> Status sensor is the value of the topic "Birth and will messages". Did you configure it properly?

I've no idea
I only know that the Yi 1080p and one outdoor if it detects them online, and the other two outdoor do not.
But I would say that I have configured all 4 the same way.

Where do I have to look at that?

**Comment by roleoroleo** [comment]
On the web page, mqtt subpage.
![immagine](https://user-images.githubusercontent.com/39277388/148574805-69201ded-bb32-4263-a458-33db7ee58b2f.png)

**Comment by roleoroleo** [comment]
In general, mqtt must be enabled.

**Comment by LeidenSpain** [comment]
Hi,

I have MQTT disabled on all cameras, the 3 outdoor and the 1080p.

I just tried turning off the camera that tells me it's online, and it's still online. So clearly it is a problem in the refreshment of the information.
It may be what you say: the MQTT

**Comment by roleoroleo** [comment]
mqtt is a requirement.

**Comment by LeidenSpain** [comment]
I have the MQTT integration installed on HA, and the MQTT enabled on the CAM
![image](https://user-images.githubusercontent.com/45803748/149669834-195d9cac-17b9-4e06-8834-b755828f13ec.png)

But, i see this on MQTT Explorer
![image](https://user-images.githubusercontent.com/45803748/149669852-d4106abb-d79a-49f9-bb5e-4b3d8db741f1.png)

What is the correct MQTT configuration of the camera?
Do we have to enter the HA section or only activate it in the general MQTT?
![image](https://user-images.githubusercontent.com/45803748/149669897-4cb14070-1595-473e-b8cd-685b7b6ec7e8.png)

**Comment by roleoroleo** [comment]
If you use this integration, you don't need to enable mqtt discovery.
Leave it disabled.
About status, set retain to 1.

**Comment by LeidenSpain** [comment]
In the end it was a problem with enabling MQTT, and the options for HA.

Thank you very much, everything seems to work now
