### ISSUE TITLE
Create sensor for triggering on motion detection image update

### ISSUE THREAD

**Issue by kyangk** [roleoroleo/yi-hack_ha_integration#71]
This is a feature request to expose a sensor for when motion detection image is updated. Currently, motion start and motion detection image are updated separately through MQTT.  If I want to send the motion detection image, triggering using the motion start is often too early since the image wouldn't have arrived yet.

Is there a better way to do this? I have to trigger using `platform: mqtt` on the MQTT topic.

**Comment by roleoroleo** [comment]
You have to use motion_detection_image: the topic where jpeg is sent from the cam.
