### ISSUE TITLE
Cache picture when loading?

### ISSUE THREAD

**Issue by kafej** [roleoroleo/yi-hack_ha_integration#72]
Hi,

Not an "issue", but maybe a feature? Implementation of some kind of camera screen cache (taken like once per 30minutes) and put it in process of loading. 

This should be very helpful because after loading element height and width can change and it's disturbing.

![obraz](https://user-images.githubusercontent.com/1838978/152244560-780fac33-bf9d-4782-ae06-b2ab491bf677.png)

**Comment by roleoroleo** [comment]
I think it's a feature related to WebRTC project.

**Comment by josecarre** [comment]
I wanted to have also this feature... it seems that the `poster:` value from webrtc should do something... but I was not able to make it work (I just want to put an static image when privacy switch is enabled). If anyone managed to do it, some hint please :)
