### ISSUE TITLE
Yi Cam performance in HA

### ISSUE THREAD

**Issue by flaleo** [roleoroleo/yi-hack_ha_integration#74]
Hi,

i have two yi cameras, one x dome and one home camera, both flashed with yi-hack-Allwinner firmware and integrated into HA with yi-hack_ha_integration. I have already tried onvif and rtsp integrations in HA with the same result.

When I start streaming from HA, the streaming really starts after about 8-9 seconds and for the first 5 seconds the stream is interrupted by buffering. The delay in streaming from live is about 10 seconds.

If, on the other hand, I try to use the onvier app on Android, the streaming starts immediately without buffering or delays.

Why is streaming from HA so bad?

My HA works on Raspberry Pi4 / 4Gb.

**Comment by roleoroleo** [comment]
Did you try this integration?
https://github.com/AlexxIT/WebRTC

**Comment by flaleo** [comment]
> Did you try this integration? https://github.com/AlexxIT/WebRTC

This integration works very well. thank you
