### ISSUE TITLE
Change the camera IP in the configuration

### ISSUE THREAD

**Issue by isbkch** [roleoroleo/yi-hack_ha_integration#78]
My system rebooted and my camera IP changed even though it was reserved... Anyway, I'm wondering how can I change the camera IP without having to reinstall it again (and loose all my preconfigured automations)

**Comment by roleoroleo** [comment]
I should implement a service discovery protocol in the cam.
But it isn't a simple task.
Are you able to set a dhcp reservation with your router?

**Comment by isbkch** [comment]
Yes, I am, it's just that sometimes when the power goes out, even my reserved addresses get reset, probably a bug with my router or something. I was just wondering where can I change the IP of an already set up camera, a file? a line in DB?

**Comment by roleoroleo** [comment]
Probably core files in the .storage directory.
But it's not safe to edit them manually.

**Comment by alexfranke** [comment]
Yeah, config\.storage\core.config_entries is where I changed the IP addresses of a few cameras after I moved them to a different vlan. I also couldn't find a mechanism to update the IP address after initially adding them. Did you get this working, @isbkch ?
