### ISSUE TITLE
Add manually camera media player

### ISSUE THREAD

**Issue by rt400** [roleoroleo/yi-hack_ha_integration#79]
Hi,
Can I add camera speaker manually instead using the integration ?
my cam add in ha from the NVR so no need the full integration.
Thanks

**Comment by roleoroleo** [comment]
You could try to create a connection with ha using the web service:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Web-services-description

**Comment by rt400** [comment]
I can't understand how to make this..
Can you provide an example ?

**Comment by roleoroleo** [comment]
It depends on what feature you need.
For example, you could create an action like in thie example:
https://developers.home-assistant.io/docs/api/rest/

Or you could use the integration and remove unused entities.
