### ISSUE TITLE
YI Dome Camera correct firmware

### ISSUE THREAD

**Issue by xelaftaki** [roleoroleo/yi-hack_ha_integration#84]
Hello people.
I've got the YI 1080P Dome Camera, with ID "A392....".
I have trouble deciding about the correct hacked firmware for my model.
I attached the corresponding photo file.

Any help would be much appreciated.
[YI_DOME_CAM_ID.pdf](https://github.com/roleoroleo/yi-hack_ha_integration/files/8695358/YI_DOME_CAM_ID.pdf)

**Comment by roleoroleo** [comment]
We need a picture of the internal boards.
And the firmware version printed in the app.

**Comment by xelaftaki** [comment]
Thank you for your response and your help friend.
As soon as i got back home, i'll send you the info.

**Comment by xelaftaki** [comment]
Hello roleoroleo.
Attached you will find the information you asked.

Thank you again, friend.

![YI_1080O_DOME_BOARD_s](https://user-images.githubusercontent.com/100031568/169648288-4195ade4-2026-4cbf-a79d-8ad663b67609.jpg)

![YI_1080O_DOME_s](https://user-images.githubusercontent.com/100031568/169648289-4fb22e70-d8fd-4a1a-bc8a-88d3e2d8c454.jpg)

![YI_1080O_DOME_FW](https://user-images.githubusercontent.com/100031568/169648333-f7e404fa-e253-46db-8d8d-d5db526f6797.jpg)

**Comment by roleoroleo** [comment]
Your cam is a Allwinner-v2: https://github.com/roleoroleo/yi-hack-Allwinner-v2
But I don't know if the hack is compatible.
Please, make a backup of the firmware and share it with me:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)

**Comment by xelaftaki** [comment]
Thanks for your response.
Attached the said firmware.

[backup_YI_dome.zip](https://github.com/roleoroleo/yi-hack_ha_integration/files/8748010/backup_YI_dome.zip)

**Comment by roleoroleo** [comment]
Your model is b091qp but it's different from other b091qp I hacked.
I will try to support it.
Could you send me manufacturer/model or other string to identify the cam?

**Comment by xelaftaki** [comment]
I'm attaching the camera's manual. Please let me know if this helps.
Thank you.
[R40GA YI YI Dome Outdoor PTZ User Manual ( Europe )_20200118.pdf](https://github.com/roleoroleo/yi-hack_ha_integration/files/8748101/R40GA.YI.YI.Dome.Outdoor.PTZ.User.Manual.Europe._20200118.pdf)

**Comment by roleoroleo** [comment]
You can use b091qp hack from releases section.
If rtsp doesn't work I need a copy of your /dev/shm/fshare_frame_buf file.

**Comment by xelaftaki** [comment]
Hello roleo.
The hack is working, as you said.
Some info, in case you need them:
1. Win10 web interface, all menus working
2. Win10, connection through ispy
3. HA, motionEye integration 
4. HA, Generic Camera integration 

As far as i can see, the only (somewhat) problem is the network delay (lag) when using the web interface to PTZ the camera.
Please let me know if you need any specific info.

Thank you again for your quick and correct response.

**Comment by roleoroleo** [comment]
Thank you for your feedback.

> As far as i can see, the only (somewhat) problem is the network delay (lag) when using the web interface to PTZ the camera.

I know but the chain of commands is long:
ptz web page -> ptz web service -> ipc_cmd command -> yi processes
and the cpu is not powerful.
