### ISSUE TITLE
Failed to setup integration: KeyError: 'TOPIC_BIRTH_WILL'

### ISSUE THREAD

**Issue by sasasalamon** [roleoroleo/yi-hack_ha_integration#87]
After adding the plugin and setting it up, HASS is showing "Failed to setup" and logs are showing the error below.
MQTT is configured on both HASS and camera. 

Logger: homeassistant.config_entries
Source: custom_components/yi_hack/__init__.py:48
Integration: Yi Cam with yi-hack ([documentation](https://github.com/roleoroleo/yi-hack_ha_integration), [issues](https://github.com/roleoroleo/yi-hack_ha_integration/issues))

Error setting up entry yi_hack_7b4bd0 for yi_hack
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/yi_hack/__init__.py", line 48, in async_setup_entry
    CONF_TOPIC_STATUS: mqtt[CONF_TOPIC_STATUS],
KeyError: 'TOPIC_BIRTH_WILL'

**Comment by roleoroleo** [comment]
Which cam are you using?
Could you share your mqtt configuration (cam side)?

**Comment by sasasalamon** [comment]
I'm using the YI cam, with MStar firmware.
Details are here:
![yi-4bd0-mqtt](https://user-images.githubusercontent.com/6216860/176178767-eec1e291-98e4-48be-a49e-c2ea94d5cd17.png)
![yi-4bd0-status](https://user-images.githubusercontent.com/6216860/176178775-5955a4c0-7d70-4620-91a7-725a6b97eeab.png)

**Comment by roleoroleo** [comment]
Based on the web interface, your fw is very old.
Try to update it to the latest version.
