### ISSUE TITLE
Initial state of baby crying sensor should not be "on"

### ISSUE THREAD

**Issue by vin-w** [roleoroleo/yi-hack_ha_integration#9]
@foxel 

I think there is a minor bug in the baby crying detection event sensor initial state.

We shouldn't assume the baby crying event is "on" at HASS startup/restart.
The next publish event received with "crying" should indicate "on" instead.

```
 $ mosquitto_sub -d -t yicam/baby_crying
Client mosqsub|11445-raspberry sending CONNECT
Client mosqsub|11445-raspberry received CONNACK (0)
Client mosqsub|11445-raspberry sending SUBSCRIBE (Mid: 1, Topic: yicam/baby_crying, QoS: 0)
Client mosqsub|11445-raspberry received SUBACK
Subscribed (mid: 1): 0
Client mosqsub|11445-raspberry received PUBLISH (d0, q0, r1, m0, 'yicam/baby_crying', ... (6 bytes))
crying                       ######## this is the value received when subscribed, should NOT consider as baby is crying
Client mosqsub|11445-raspberry sending PINGREQ
Client mosqsub|11445-raspberry received PINGRESP
Client mosqsub|11445-raspberry sending PINGREQ
Client mosqsub|11445-raspberry received PINGRESP
Client mosqsub|11445-raspberry received PUBLISH (d0, q0, r0, m0, 'yicam/baby_crying', ... (6 bytes))
crying                       ######## this is a new baby crying event, make sensor "on" and make it "off" after 60 sec.
Client mosqsub|11445-raspberry sending PINGREQ
Client mosqsub|11445-raspberry received PINGRESP
Client mosqsub|11445-raspberry sending PINGREQ
```

binary_sensor.yi_hack_XX_baby_crying is now false alarm "on" for 1 min on startup
and wait for _off_delay = 60 to "off"

**Comment by vin-w** [comment]
Created pull request https://github.com/roleoroleo/yi-hack_ha_integration/pull/10

**Comment by foxel** [comment]
You need to disable retain and clear the topic. The first value you get is the retained one. This is how mqtt works

**Comment by vin-w** [comment]
@foxel, thanks for pointing out about retain.

@roleoroleo, why there is no retain setting for baby crying event in http://my_ip:8080/?page=mqtt
I am using  0.2.5 all winner hack. Perhaps a fix on this could fix the HA integration issue.

```
Under Advanced
Retain for birth and will messages | 
Retain for motion messages | 
Retain for motion image messages | 
Retain for video list messages | 
Retain for AI Human Detection messages | 
Retain for Sound Detection messages | 
```

**Comment by roleoroleo** [comment]
> @roleoroleo, do you know why there is no retain setting for baby crying event in http://my_ip:8080/?page=mqtt
> I am using v0.2.5 yi-hack-Allwinner.

Ooops. 
It's an error.
