### ISSUE TITLE
"Yi Cam with yi-hack" doesn't show up in integration

### ISSUE THREAD

**Issue by NecoH3ll** [roleoroleo/yi-hack_ha_integration#92]
Hello, i'm very new to HA..

I installed HA Supervised and wanted to install the Yi-Cam Hack Addon.. 
I'm running: 
![image](https://user-images.githubusercontent.com/104097236/185969176-f24d406a-28d6-4205-bbca-6812988ae9ed.png)

somehow it doesn't show up in integrations - i'm not sure tho, if I put the custom_components in the right folder.
I put it here:
![image](https://user-images.githubusercontent.com/104097236/185969337-dd23b569-06ce-433b-bb4a-28ce77ee7bfb.png)

while the folder path looks like this:
![image](https://user-images.githubusercontent.com/104097236/185969466-bdce7696-0259-4be6-9a51-962b060d2a00.png)

The HA-integration Manager shows something like this:
![image](https://user-images.githubusercontent.com/104097236/185969611-dedf88ed-15b8-4d48-ab0b-5c53f5997eb4.png)
It says that there couldn't be found any integration.
I also resartet HA as it says in the instructions and even restarted the whole system.

Oli

**Comment by roleoroleo** [comment]
The folder is ok.
It should work.

Or, if you have it, try with HACS.

**Comment by NecoH3ll** [comment]
It worked with the HACS - thanks a lot for the fast response!
