### ISSUE TITLE
Please create a release including the fix for baby crying

### ISSUE THREAD

**Issue by ak6i** [roleoroleo/yi-hack_ha_integration#95]
When trying to create a new integration in Home Assistant using version 0.3.9 of yi-hack_ha_integration and a camera with 0.2.3 of yi-hack-Allwinnerv2, setup fails with the following error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/yi_hack/__init__.py", line 65, in async_setup_entry
    CONF_TOPIC_BABY_CRYING: mqtt[CONF_TOPIC_BABY_CRYING],
KeyError: 'TOPIC_BABY_CRYING’

I'd update manually but I don't know how to get the version from main into HACS.  Please press the release button so magic can happen! :)

**Comment by roleoroleo** [comment]
Done.

**Comment by gbwin** [comment]
Hi, I've the same issue, how can i fix it please ?

**Comment by roleoroleo** [comment]
Use the last released version.
